"""
amls_models.py — Data models for the Autonomous Market Learning Scheduler.

MLS Phase 6: AMLS.

Pure data.  No business logic.  All fields JSON-serialisable.
This module is the single source of truth for every AMLS model definition.
No computation or scheduling logic lives here.
"""
from __future__ import annotations

from dataclasses import dataclass, field
from enum import Enum
from typing import Any, Dict, List, Optional


# ─── pipeline state ──────────────────────────────────────────────────────────

class PipelineState(str, Enum):
    """Lifecycle state of an AMLS pipeline run or individual stage."""
    WAITING = "WAITING"   # scheduled but not yet started
    RUNNING = "RUNNING"   # currently executing
    SUCCESS = "SUCCESS"   # all required stages completed successfully
    FAILED  = "FAILED"    # all stages failed or required stage failed fatally
    SKIPPED = "SKIPPED"   # not a trading day, or upstream dependency missing
    PARTIAL = "PARTIAL"   # some stages succeeded, some failed


# ─── stage name constants ────────────────────────────────────────────────────

STAGE_SNAPSHOT    = "snapshot_capture"
STAGE_CLASSIFY    = "population_classify"
STAGE_DISCOVER    = "dna_discover"
STAGE_CONSENSUS   = "dna_consensus"
STAGE_IDR_SYNC    = "idr_sync"
STAGE_PIG_REFRESH = "pig_refresh"
STAGE_REPORT      = "generate_report"

# Ordered execution sequence
ALL_STAGES: List[str] = [
    STAGE_SNAPSHOT,
    STAGE_CLASSIFY,
    STAGE_DISCOVER,
    STAGE_CONSENSUS,
    STAGE_IDR_SYNC,
    STAGE_PIG_REFRESH,
    STAGE_REPORT,
]

# Stages that always run regardless of upstream failures
ALWAYS_RUN_STAGES: frozenset = frozenset({STAGE_PIG_REFRESH, STAGE_REPORT})


# ─── PipelineFailure ─────────────────────────────────────────────────────────

@dataclass
class PipelineFailure:
    """Error record for a single failed stage execution."""
    stage_name:        str
    error_type:        str    # type(exception).__name__
    error_message:     str
    retries_attempted: int
    timestamp:         str    # ISO datetime of failure

    def to_dict(self) -> Dict[str, Any]:
        return {
            "stage_name":        self.stage_name,
            "error_type":        self.error_type,
            "error_message":     self.error_message,
            "retries_attempted": self.retries_attempted,
            "timestamp":         self.timestamp,
        }

    @classmethod
    def from_dict(cls, d: Dict[str, Any]) -> PipelineFailure:
        return cls(
            stage_name=d["stage_name"],
            error_type=d["error_type"],
            error_message=d["error_message"],
            retries_attempted=int(d.get("retries_attempted", 0)),
            timestamp=d["timestamp"],
        )


# ─── PipelineStage ───────────────────────────────────────────────────────────

@dataclass
class PipelineStage:
    """Execution record for one named pipeline stage."""
    name:           str
    state:          PipelineState
    start_time:     Optional[str]    # ISO datetime
    end_time:       Optional[str]    # ISO datetime
    duration_ms:    Optional[float]
    retry_count:    int
    output_summary: str              # human-readable result description
    failure:        Optional[PipelineFailure]

    def to_dict(self) -> Dict[str, Any]:
        return {
            "name":           self.name,
            "state":          self.state.value,
            "start_time":     self.start_time,
            "end_time":       self.end_time,
            "duration_ms":    self.duration_ms,
            "retry_count":    self.retry_count,
            "output_summary": self.output_summary,
            "failure":        self.failure.to_dict() if self.failure else None,
        }

    @classmethod
    def from_dict(cls, d: Dict[str, Any]) -> PipelineStage:
        return cls(
            name=d["name"],
            state=PipelineState(d["state"]),
            start_time=d.get("start_time"),
            end_time=d.get("end_time"),
            duration_ms=d.get("duration_ms"),
            retry_count=int(d.get("retry_count", 0)),
            output_summary=d.get("output_summary", ""),
            failure=PipelineFailure.from_dict(d["failure"]) if d.get("failure") else None,
        )


# ─── PipelineTelemetry ───────────────────────────────────────────────────────

@dataclass
class PipelineTelemetry:
    """
    Complete execution telemetry for one AMLS pipeline run.

    Generated by the generate_report stage.  Always emitted, even on failure.
    """
    run_id:             str
    trading_date:       str        # YYYY-MM-DD
    start_time:         str        # ISO datetime
    end_time:           str        # ISO datetime
    total_duration_ms:  float
    pipeline_state:     str        # PipelineState.value
    success:            bool
    stages_success:     int
    stages_failed:      int
    stages_skipped:     int
    total_retry_count:  int
    knowledge_generated: bool      # True if DNA characteristics discovered
    dna_updated:        bool       # True if ConsensusLibrary written
    repository_writes:  int        # IDR.save() calls completed
    gateway_refreshed:  bool       # PIGTradingAdapter.reload_library() called
    failures:           List[PipelineFailure]

    def to_dict(self) -> Dict[str, Any]:
        return {
            "run_id":             self.run_id,
            "trading_date":       self.trading_date,
            "start_time":         self.start_time,
            "end_time":           self.end_time,
            "total_duration_ms":  self.total_duration_ms,
            "pipeline_state":     self.pipeline_state,
            "success":            self.success,
            "stages_success":     self.stages_success,
            "stages_failed":      self.stages_failed,
            "stages_skipped":     self.stages_skipped,
            "total_retry_count":  self.total_retry_count,
            "knowledge_generated": self.knowledge_generated,
            "dna_updated":        self.dna_updated,
            "repository_writes":  self.repository_writes,
            "gateway_refreshed":  self.gateway_refreshed,
            "failures":           [f.to_dict() for f in self.failures],
        }

    @classmethod
    def from_dict(cls, d: Dict[str, Any]) -> PipelineTelemetry:
        return cls(
            run_id=d["run_id"],
            trading_date=d["trading_date"],
            start_time=d["start_time"],
            end_time=d["end_time"],
            total_duration_ms=float(d.get("total_duration_ms", 0.0)),
            pipeline_state=d.get("pipeline_state", "UNKNOWN"),
            success=bool(d.get("success", False)),
            stages_success=int(d.get("stages_success", 0)),
            stages_failed=int(d.get("stages_failed", 0)),
            stages_skipped=int(d.get("stages_skipped", 0)),
            total_retry_count=int(d.get("total_retry_count", 0)),
            knowledge_generated=bool(d.get("knowledge_generated", False)),
            dna_updated=bool(d.get("dna_updated", False)),
            repository_writes=int(d.get("repository_writes", 0)),
            gateway_refreshed=bool(d.get("gateway_refreshed", False)),
            failures=[PipelineFailure.from_dict(f) for f in d.get("failures", [])],
        )


# ─── MLSPipelineRun ──────────────────────────────────────────────────────────

@dataclass
class MLSPipelineRun:
    """Complete record of one AMLS pipeline execution."""
    run_id:           str
    trading_date:     str             # YYYY-MM-DD
    state:            PipelineState
    stages:           List[PipelineStage]
    started_at:       Optional[str]   # ISO datetime
    ended_at:         Optional[str]   # ISO datetime
    total_duration_ms: Optional[float]
    telemetry:        Optional[PipelineTelemetry]

    # ── derived helpers ──────────────────────────────────────────────────────

    def get_stage(self, name: str) -> Optional[PipelineStage]:
        """Return the named stage, or None if absent."""
        for s in self.stages:
            if s.name == name:
                return s
        return None

    def failed_stages(self) -> List[PipelineStage]:
        return [s for s in self.stages if s.state == PipelineState.FAILED]

    def successful_stages(self) -> List[PipelineStage]:
        return [s for s in self.stages if s.state == PipelineState.SUCCESS]

    # ── serialisation ────────────────────────────────────────────────────────

    def to_dict(self) -> Dict[str, Any]:
        return {
            "run_id":            self.run_id,
            "trading_date":      self.trading_date,
            "state":             self.state.value,
            "stages":            [s.to_dict() for s in self.stages],
            "started_at":        self.started_at,
            "ended_at":          self.ended_at,
            "total_duration_ms": self.total_duration_ms,
            "telemetry":         self.telemetry.to_dict() if self.telemetry else None,
        }

    @classmethod
    def from_dict(cls, d: Dict[str, Any]) -> MLSPipelineRun:
        return cls(
            run_id=d["run_id"],
            trading_date=d["trading_date"],
            state=PipelineState(d["state"]),
            stages=[PipelineStage.from_dict(s) for s in d.get("stages", [])],
            started_at=d.get("started_at"),
            ended_at=d.get("ended_at"),
            total_duration_ms=d.get("total_duration_ms"),
            telemetry=PipelineTelemetry.from_dict(d["telemetry"]) if d.get("telemetry") else None,
        )


# ─── PipelineStatistics ──────────────────────────────────────────────────────

@dataclass
class PipelineStatistics:
    """Aggregate statistics computed from AMLS run history."""
    total_runs:          int
    successful_runs:     int
    failed_runs:         int
    partial_runs:        int
    skipped_runs:        int
    avg_duration_ms:     float
    total_dna_updates:   int
    total_idr_writes:    int
    total_retries:       int
    success_rate:        float    # successful / (total - skipped); 0.0 if no runs
    last_successful_run: Optional[str]   # ISO date YYYY-MM-DD
    last_failed_run:     Optional[str]   # ISO date YYYY-MM-DD

    def to_dict(self) -> Dict[str, Any]:
        return {
            "total_runs":          self.total_runs,
            "successful_runs":     self.successful_runs,
            "failed_runs":         self.failed_runs,
            "partial_runs":        self.partial_runs,
            "skipped_runs":        self.skipped_runs,
            "avg_duration_ms":     self.avg_duration_ms,
            "total_dna_updates":   self.total_dna_updates,
            "total_idr_writes":    self.total_idr_writes,
            "total_retries":       self.total_retries,
            "success_rate":        self.success_rate,
            "last_successful_run": self.last_successful_run,
            "last_failed_run":     self.last_failed_run,
        }

    @classmethod
    def from_dict(cls, d: Dict[str, Any]) -> PipelineStatistics:
        return cls(
            total_runs=int(d.get("total_runs", 0)),
            successful_runs=int(d.get("successful_runs", 0)),
            failed_runs=int(d.get("failed_runs", 0)),
            partial_runs=int(d.get("partial_runs", 0)),
            skipped_runs=int(d.get("skipped_runs", 0)),
            avg_duration_ms=float(d.get("avg_duration_ms", 0.0)),
            total_dna_updates=int(d.get("total_dna_updates", 0)),
            total_idr_writes=int(d.get("total_idr_writes", 0)),
            total_retries=int(d.get("total_retries", 0)),
            success_rate=float(d.get("success_rate", 0.0)),
            last_successful_run=d.get("last_successful_run"),
            last_failed_run=d.get("last_failed_run"),
        )


# ─── PipelineHealth ──────────────────────────────────────────────────────────

@dataclass
class PipelineHealth:
    """
    Health diagnostic snapshot for the AMLS pipeline.

    healthy=True means the pipeline ran successfully recently and all
    data stores are in consistent state.
    """
    healthy:              bool
    issues:               List[str]
    pipeline_state:       str         # PipelineState.value of last run (or WAITING)
    last_run_date:        Optional[str]
    last_success_date:    Optional[str]
    days_since_success:   Optional[int]
    missing_snapshot:     bool        # today's snapshot not found on disk
    missing_dna:          bool        # no DNA in ConsensusLibrary
    repository_ok:        bool        # IDR accessible
    gateway_ok:           bool        # PIG adapter loaded
    pipeline_interrupted: bool        # last run ended in RUNNING or PARTIAL state

    def to_dict(self) -> Dict[str, Any]:
        return {
            "healthy":              self.healthy,
            "issues":               self.issues,
            "pipeline_state":       self.pipeline_state,
            "last_run_date":        self.last_run_date,
            "last_success_date":    self.last_success_date,
            "days_since_success":   self.days_since_success,
            "missing_snapshot":     self.missing_snapshot,
            "missing_dna":          self.missing_dna,
            "repository_ok":        self.repository_ok,
            "gateway_ok":           self.gateway_ok,
            "pipeline_interrupted": self.pipeline_interrupted,
        }
