"""
idr_models.py — Pure data models for the Institutional DNA Repository.

R-013: Institutional DNA Repository.

Pure data.  No business logic.  All fields JSON-serialisable.
IDR = Institutional DNA Repository — the permanent persistence layer
for all institutional DNA knowledge generated by MLS.

This module is the only source of truth for IDR model definitions.
No DNA calculation lives here.  Persistence logic lives in idr_repository.py.
"""
from __future__ import annotations

import json
from dataclasses import dataclass, field
from typing import Any, Dict, List, Optional


# ─── exceptions ───────────────────────────────────────────────────────────────

class IDRError(Exception):
    """Base exception for all IDR errors."""


class IDRNotFoundError(IDRError):
    """DNA id not found in the repository."""


class IDRVersionError(IDRError):
    """Requested DNA version does not exist."""


class IDRIntegrityError(IDRError):
    """Repository integrity check failed."""


# ─── InstitutionalDNA ─────────────────────────────────────────────────────────

@dataclass
class InstitutionalDNA:
    """
    A single DNA record as stored in the Institutional DNA Repository.

    One record per (id, version) pair.  The latest version has is_current=True.
    Never overwrite — every update creates a new version.
    """

    id:                    str                    # stable DNA identity key
    feature_name:          str                    # e.g. "rsi_5d"
    direction:             str                    # SeparationDirection value
    category:              str                    # WINNER / LOSER / NEUTRAL / CONSENSUS
    lifecycle:             str                    # ConsensusState value
    version:               int                    # monotonically increasing from 1
    consensus_score:       float                  # [0, 1]
    confidence:            float                  # [0, 1]
    effect_size:           float                  # |Cohen's d|
    regime_consistency:    float                  # [0, 1]
    sector_consistency:    float                  # [0, 1]
    temporal_stability:    float                  # [0, 1]
    replication_frequency: float                  # [0, 1]
    evidence_count:        int
    regime_counts:         Dict[str, int]         # regime label → observed count
    last_seen:             Optional[str]          # ISO date of last observation
    study_id:              str                    # originating study / replay id
    source:                str                    # discovery engine version / tag
    created_at:            str                    # ISO datetime of first creation
    updated_at:            str                    # ISO datetime of this version
    is_current:            bool                   # True = latest version of this id
    metadata:              Dict[str, Any]         # arbitrary extra fields

    # ── serialisation ────────────────────────────────────────────────────────

    def to_dict(self) -> Dict[str, Any]:
        return {
            "id":                    self.id,
            "feature_name":          self.feature_name,
            "direction":             self.direction,
            "category":              self.category,
            "lifecycle":             self.lifecycle,
            "version":               self.version,
            "consensus_score":       self.consensus_score,
            "confidence":            self.confidence,
            "effect_size":           self.effect_size,
            "regime_consistency":    self.regime_consistency,
            "sector_consistency":    self.sector_consistency,
            "temporal_stability":    self.temporal_stability,
            "replication_frequency": self.replication_frequency,
            "evidence_count":        self.evidence_count,
            "regime_counts":         self.regime_counts,
            "last_seen":             self.last_seen,
            "study_id":              self.study_id,
            "source":                self.source,
            "created_at":            self.created_at,
            "updated_at":            self.updated_at,
            "is_current":            self.is_current,
            "metadata":              self.metadata,
        }

    @classmethod
    def from_dict(cls, d: Dict[str, Any]) -> "InstitutionalDNA":
        return cls(
            id=d["id"],
            feature_name=d["feature_name"],
            direction=d["direction"],
            category=d["category"],
            lifecycle=d["lifecycle"],
            version=int(d["version"]),
            consensus_score=float(d["consensus_score"]),
            confidence=float(d["confidence"]),
            effect_size=float(d["effect_size"]),
            regime_consistency=float(d["regime_consistency"]),
            sector_consistency=float(d["sector_consistency"]),
            temporal_stability=float(d["temporal_stability"]),
            replication_frequency=float(d["replication_frequency"]),
            evidence_count=int(d["evidence_count"]),
            regime_counts={str(k): int(v) for k, v in d.get("regime_counts", {}).items()},
            last_seen=d.get("last_seen"),
            study_id=d.get("study_id", ""),
            source=d.get("source", ""),
            created_at=d.get("created_at", ""),
            updated_at=d.get("updated_at", ""),
            is_current=bool(d.get("is_current", True)),
            metadata=d.get("metadata", {}),
        )

    # ── convenience ──────────────────────────────────────────────────────────

    @property
    def is_institutional(self) -> bool:
        return self.lifecycle in ("INSTITUTIONAL", "WEAKENING", "DRIFTING")

    @property
    def is_retired(self) -> bool:
        return self.lifecycle == "RETIRED"


# ─── DNARevision ──────────────────────────────────────────────────────────────

@dataclass
class DNARevision:
    """
    Record of a single versioning event in the IDR.

    Every save(), update(), or retire() produces a DNARevision that describes
    exactly what changed and why.
    """

    dna_id:           str
    version:          int
    previous_version: Optional[int]         # None for the first version
    operation:        str                   # CREATED / UPDATED / RETIRED
    reason:           str
    study_id:         str
    operator:         str
    timestamp:        str                   # ISO datetime
    changes:          Dict[str, Any]        # field_name → new_value

    def to_dict(self) -> Dict[str, Any]:
        return {
            "dna_id":           self.dna_id,
            "version":          self.version,
            "previous_version": self.previous_version,
            "operation":        self.operation,
            "reason":           self.reason,
            "study_id":         self.study_id,
            "operator":         self.operator,
            "timestamp":        self.timestamp,
            "changes":          self.changes,
        }

    @classmethod
    def from_dict(cls, d: Dict[str, Any]) -> "DNARevision":
        return cls(
            dna_id=d["dna_id"],
            version=int(d["version"]),
            previous_version=int(d["previous_version"]) if d.get("previous_version") is not None else None,
            operation=d["operation"],
            reason=d.get("reason", ""),
            study_id=d.get("study_id", ""),
            operator=d.get("operator", "system"),
            timestamp=d["timestamp"],
            changes=d.get("changes", {}),
        )


# ─── DNAEvidence ──────────────────────────────────────────────────────────────

@dataclass
class DNAEvidence:
    """
    One piece of statistical evidence supporting or weakening a DNA pattern.

    Evidence is immutable — it is never updated.  New evidence is appended.
    Multiple evidence records build the audit trail of confidence evolution.
    """

    dna_id:           str
    dna_version:      int
    study_id:         str
    source:           str
    sample_size:      int
    effect_size:      float
    confidence:       float
    regime:           str
    sector:           str
    observation_date: str             # ISO date
    id:               int = 0         # 0 = not yet persisted; set by repository
    p_value:          Optional[float] = None
    ci_low:           Optional[float] = None
    ci_high:          Optional[float] = None
    created_at:       str = ""
    metadata:         Dict[str, Any] = field(default_factory=dict)

    def to_dict(self) -> Dict[str, Any]:
        return {
            "id":               self.id,
            "dna_id":           self.dna_id,
            "dna_version":      self.dna_version,
            "study_id":         self.study_id,
            "source":           self.source,
            "sample_size":      self.sample_size,
            "effect_size":      self.effect_size,
            "confidence":       self.confidence,
            "regime":           self.regime,
            "sector":           self.sector,
            "p_value":          self.p_value,
            "ci_low":           self.ci_low,
            "ci_high":          self.ci_high,
            "observation_date": self.observation_date,
            "created_at":       self.created_at,
            "metadata":         self.metadata,
        }

    @classmethod
    def from_dict(cls, d: Dict[str, Any]) -> "DNAEvidence":
        return cls(
            id=int(d.get("id", 0)),
            dna_id=d["dna_id"],
            dna_version=int(d["dna_version"]),
            study_id=d.get("study_id", ""),
            source=d.get("source", ""),
            sample_size=int(d["sample_size"]),
            effect_size=float(d["effect_size"]),
            confidence=float(d["confidence"]),
            regime=d.get("regime", ""),
            sector=d.get("sector", ""),
            p_value=float(d["p_value"]) if d.get("p_value") is not None else None,
            ci_low=float(d["ci_low"]) if d.get("ci_low") is not None else None,
            ci_high=float(d["ci_high"]) if d.get("ci_high") is not None else None,
            observation_date=d["observation_date"],
            created_at=d.get("created_at", ""),
            metadata=d.get("metadata", {}),
        )


# ─── DNAHistory ───────────────────────────────────────────────────────────────

@dataclass
class DNAHistory:
    """
    A time-series record of a DNA pattern's key metrics on a specific date.

    Answers: what was the confidence / consensus / drift / lifecycle of this
    DNA on a given day?  Supports reconstruction of any historical DNA state.
    """

    dna_id:          str
    history_date:    str             # ISO date
    confidence:      float
    consensus_score: float
    drift:           float           # measured drift magnitude [0, 1]
    stability:       float           # temporal stability [0, 1]
    relevance:       str             # DNARelevance value or empty string
    lifecycle:       str             # ConsensusState value at this date
    version_at_time: int             # DNA version active on this date
    id:              int = 0         # 0 = not yet persisted; set by repository
    created_at:      str = ""

    def to_dict(self) -> Dict[str, Any]:
        return {
            "id":              self.id,
            "dna_id":          self.dna_id,
            "history_date":    self.history_date,
            "confidence":      self.confidence,
            "consensus_score": self.consensus_score,
            "drift":           self.drift,
            "stability":       self.stability,
            "relevance":       self.relevance,
            "lifecycle":       self.lifecycle,
            "version_at_time": self.version_at_time,
            "created_at":      self.created_at,
        }

    @classmethod
    def from_dict(cls, d: Dict[str, Any]) -> "DNAHistory":
        return cls(
            id=int(d.get("id", 0)),
            dna_id=d["dna_id"],
            history_date=d["history_date"],
            confidence=float(d["confidence"]),
            consensus_score=float(d["consensus_score"]),
            drift=float(d.get("drift", 0.0)),
            stability=float(d.get("stability", 0.0)),
            relevance=d.get("relevance", ""),
            lifecycle=d["lifecycle"],
            version_at_time=int(d["version_at_time"]),
            created_at=d.get("created_at", ""),
        )


# ─── DNAContext ───────────────────────────────────────────────────────────────

@dataclass
class DNAContext:
    """
    A snapshot of market-context dimensions associated with a DNA observation.

    Enables CDS historical analogue matching: find dates where the DNA
    was active in a similar market context.
    """

    dna_id:               str
    dna_version:          int
    regime:               str
    volatility:           float          # [0, 1]
    breadth:              float          # [0, 1]
    sector:               float          # [0, 1]
    liquidity:            float          # [0, 1]
    institutional:        float          # [0, 1]
    historical_similarity: float         # [0, 1] — match to current context
    context_date:         str            # ISO date
    id:                   int = 0
    created_at:           str = ""

    def to_dict(self) -> Dict[str, Any]:
        return {
            "id":                    self.id,
            "dna_id":                self.dna_id,
            "dna_version":           self.dna_version,
            "regime":                self.regime,
            "volatility":            self.volatility,
            "breadth":               self.breadth,
            "sector":                self.sector,
            "liquidity":             self.liquidity,
            "institutional":         self.institutional,
            "historical_similarity": self.historical_similarity,
            "context_date":          self.context_date,
            "created_at":            self.created_at,
        }

    @classmethod
    def from_dict(cls, d: Dict[str, Any]) -> "DNAContext":
        return cls(
            id=int(d.get("id", 0)),
            dna_id=d["dna_id"],
            dna_version=int(d["dna_version"]),
            regime=d.get("regime", ""),
            volatility=float(d.get("volatility", 0.0)),
            breadth=float(d.get("breadth", 0.0)),
            sector=float(d.get("sector", 0.0)),
            liquidity=float(d.get("liquidity", 0.0)),
            institutional=float(d.get("institutional", 0.0)),
            historical_similarity=float(d.get("historical_similarity", 0.0)),
            context_date=d["context_date"],
            created_at=d.get("created_at", ""),
        )


# ─── DNARepositoryStatistics ──────────────────────────────────────────────────

@dataclass
class DNARepositoryStatistics:
    """Aggregated statistics for the Institutional DNA Repository."""

    total_dna:            int
    active_dna:           int
    retired_dna:          int
    institutional_dna:    int
    weakening_dna:        int
    drifting_dna:         int
    total_evidence:       int
    total_history_points: int
    total_versions:       int
    avg_confidence:       float
    avg_consensus_score:  float
    schema_version:       int
    last_updated:         str
    db_size_bytes:        int

    def to_dict(self) -> Dict[str, Any]:
        return {
            "total_dna":            self.total_dna,
            "active_dna":           self.active_dna,
            "retired_dna":          self.retired_dna,
            "institutional_dna":    self.institutional_dna,
            "weakening_dna":        self.weakening_dna,
            "drifting_dna":         self.drifting_dna,
            "total_evidence":       self.total_evidence,
            "total_history_points": self.total_history_points,
            "total_versions":       self.total_versions,
            "avg_confidence":       self.avg_confidence,
            "avg_consensus_score":  self.avg_consensus_score,
            "schema_version":       self.schema_version,
            "last_updated":         self.last_updated,
            "db_size_bytes":        self.db_size_bytes,
        }

    @classmethod
    def empty(cls) -> "DNARepositoryStatistics":
        """Return a zero-filled statistics record."""
        return cls(
            total_dna=0, active_dna=0, retired_dna=0,
            institutional_dna=0, weakening_dna=0, drifting_dna=0,
            total_evidence=0, total_history_points=0, total_versions=0,
            avg_confidence=0.0, avg_consensus_score=0.0,
            schema_version=1, last_updated="", db_size_bytes=0,
        )
