"""
tests/test_governance_remediation.py â€” G-001/G-002/G-003/G-004 Regression Tests

Coverage (14 tests):
  GR-001  Strategy enters EARLY_ABORT_LOW_WR
  GR-002  Strategy remains disabled during cooldown
  GR-003  Cooldown expires â†’ revalidation_pending set
  GR-004  Strategy is NOT automatically enabled after cooldown
  GR-005  Failed revalidation keeps strategy disabled
  GR-006  Successful revalidation goes through normal promotion governance
  GR-007  Revalidation is idempotent (tick_session called multiple times)
  GR-008  Synthetic/live divergence creates research action
  GR-009  No duplicate research actions for same open investigation
  GR-010  G-003: Evolved variant audit log when base excluded and variant absent
  GR-011  G-003: Evolved variant returned when base excluded but variant in active
  GR-012  G-004: Regime metadata attached to future trades
  GR-013  Existing live trading behavior unchanged (disabled strategies stay disabled)
  GR-014  No live order generated by any governance/research process

Run with:  python -m pytest tests/test_governance_remediation.py -v
"""
from __future__ import annotations

import json
import os
import sys
import tempfile
import types
import unittest
from unittest.mock import MagicMock, patch

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, ROOT)


# â”€â”€ Stub heavy dependencies before any project import â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€

def _stub(name, **attrs):
    mod = types.ModuleType(name)
    for k, v in attrs.items():
        setattr(mod, k, v)
    sys.modules.setdefault(name, mod)
    return mod


_stub("utils", get_logger=MagicMock(return_value=MagicMock()))


# â”€â”€ Import SHM and divergence detector after stubs are registered â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€

from trade_monitoring.strategy_health_monitor import (
    StrategyHealthMonitor,
    StrategyHealthRecord,
    HealthStatus,
    HEALTH_DB_PATH,
    EARLY_ABORT_MIN_TRADES,
    EARLY_ABORT_COOLDOWN,
    EARLY_ABORT_MAX_WR,
    EARLY_ABORT_MIN_TOTAL_R,
    MIN_TRADES,
    DISABLE_REASON_EARLY_ABORT,
)
from trade_monitoring.performance_divergence_detector import (
    PerformanceDivergenceDetector,
    DivergenceConfig,
    STATUS_RESEARCH_REQUIRED,
    STATUS_UNDER_INVESTIGATION,
)


# â”€â”€ Helpers â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€

def _make_shm(tmpdir: str) -> StrategyHealthMonitor:
    """Create a StrategyHealthMonitor backed by a temp directory."""
    import trade_monitoring.strategy_health_monitor as _shm_mod
    orig = _shm_mod.HEALTH_DB_PATH
    _shm_mod.HEALTH_DB_PATH = os.path.join(tmpdir, "strategy_health.json")
    try:
        shm = StrategyHealthMonitor()
    finally:
        _shm_mod.HEALTH_DB_PATH = orig
    # Bind instance to temp path for save/load
    shm._db_path = os.path.join(tmpdir, "strategy_health.json")
    # Monkey-patch save/load to use temp path
    import trade_monitoring.strategy_health_monitor as _m
    _orig_save = _m.StrategyHealthMonitor._save_db
    _orig_load = _m.StrategyHealthMonitor._load_db

    def _save(self_inner):
        try:
            with open(self_inner._db_path, "w", encoding="utf-8") as f:
                json.dump(
                    {k: v.to_dict() for k, v in self_inner._records.items()},
                    f, indent=2,
                )
        except Exception:
            pass

    def _load(self_inner):
        p = self_inner._db_path
        if not os.path.exists(p):
            return
        try:
            with open(p, "r", encoding="utf-8") as f:
                raw = json.load(f)
            for k, v in raw.items():
                self_inner._records[k] = StrategyHealthRecord.from_dict(v)
        except Exception:
            pass

    shm._save_db = lambda: _save(shm)
    shm._load_db = lambda: _load(shm)
    return shm


def _make_detector(tmpdir: str, **cfg_kwargs) -> PerformanceDivergenceDetector:
    """Create a PerformanceDivergenceDetector backed by a temp directory."""
    import trade_monitoring.performance_divergence_detector as _dd_mod
    orig = _dd_mod.INVESTIGATIONS_PATH
    _dd_mod.INVESTIGATIONS_PATH = os.path.join(tmpdir, "divergence.json")
    try:
        cfg = DivergenceConfig(**cfg_kwargs)
        det = PerformanceDivergenceDetector(config=cfg)
    finally:
        _dd_mod.INVESTIGATIONS_PATH = orig
    det._inv_path = os.path.join(tmpdir, "divergence.json")

    def _save_det(self_inner):
        try:
            with open(self_inner._inv_path, "w") as f:
                json.dump({k: v.to_dict() for k, v in self_inner._investigations.items()}, f)
        except Exception:
            pass

    det._save = lambda: _save_det(det)
    return det


# â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•
# G-001 Tests â€” EARLY_ABORT Deadlock Resolution
# â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•

class TestG001EarlyAbortDeadlock(unittest.TestCase):

    def setUp(self):
        self.tmpdir = tempfile.mkdtemp()
        self.shm = _make_shm(self.tmpdir)

    def _drive_to_early_abort(self):
        """Record 9 losing trades to trigger EARLY_ABORT."""
        for _ in range(9):
            self.shm.record_trade("Mean_Reversion", -0.02, -1.0)

    def test_gr001_strategy_enters_early_abort(self):
        """GR-001: After 9 losing trades, Mean_Reversion is DISABLED via EARLY_ABORT."""
        self._drive_to_early_abort()
        self.assertIn("Mean_Reversion", self.shm.get_disabled_strategies())
        rec = self.shm._records["Mean_Reversion"]
        self.assertEqual(rec.disabled_reason, DISABLE_REASON_EARLY_ABORT)

    def test_gr002_strategy_remains_disabled_during_cooldown(self):
        """GR-002: Strategy stays in disabled set during cooldown."""
        self._drive_to_early_abort()
        for _ in range(EARLY_ABORT_COOLDOWN - 1):
            self.shm.tick_session()
        self.assertIn("Mean_Reversion", self.shm.get_disabled_strategies())

    def test_gr003_cooldown_expiry_sets_revalidation_pending(self):
        """GR-003: After cooldown, revalidation_pending becomes True."""
        self._drive_to_early_abort()
        for _ in range(EARLY_ABORT_COOLDOWN):
            self.shm.tick_session()
        rec = self.shm._records["Mean_Reversion"]
        self.assertTrue(rec.revalidation_pending)
        self.assertIsNotNone(rec.revalidation_timestamp)

    def test_gr004_strategy_not_auto_enabled_after_cooldown(self):
        """GR-004: Strategy must NOT appear in passing set after cooldown expires."""
        self._drive_to_early_abort()
        for _ in range(EARLY_ABORT_COOLDOWN):
            self.shm.tick_session()
        self.assertIn("Mean_Reversion", self.shm.get_disabled_strategies(),
                      "Strategy must remain DISABLED after cooldown expiry")

    def test_gr005_failed_revalidation_keeps_strategy_disabled(self):
        """GR-005: mark_revalidation_complete(FAIL) leaves strategy disabled."""
        self._drive_to_early_abort()
        for _ in range(EARLY_ABORT_COOLDOWN):
            self.shm.tick_session()
        self.shm.mark_revalidation_complete("Mean_Reversion", "FAIL", "metrics still poor")
        rec = self.shm._records["Mean_Reversion"]
        self.assertEqual(rec.revalidation_result, "FAIL")
        self.assertFalse(rec.revalidation_pending)
        self.assertIn("Mean_Reversion", self.shm.get_disabled_strategies())

    def test_gr006_successful_revalidation_requires_normal_promotion(self):
        """GR-006: PASS result does NOT auto-enable strategy."""
        self._drive_to_early_abort()
        for _ in range(EARLY_ABORT_COOLDOWN):
            self.shm.tick_session()
        self.shm.mark_revalidation_complete("Mean_Reversion", "PASS", "sampling artifact")
        rec = self.shm._records["Mean_Reversion"]
        self.assertEqual(rec.revalidation_result, "PASS")
        self.assertFalse(rec.revalidation_pending)
        # Still disabled â€” PASS alone is not sufficient
        self.assertIn("Mean_Reversion", self.shm.get_disabled_strategies(),
                      "PASS result alone must not re-enable the strategy")

    def test_gr007_revalidation_is_idempotent(self):
        """GR-007: Extra tick_session calls do not create duplicate revalidation requests."""
        self._drive_to_early_abort()
        for _ in range(EARLY_ABORT_COOLDOWN):
            self.shm.tick_session()
        ts1 = self.shm._records["Mean_Reversion"].revalidation_timestamp
        # Extra ticks
        self.shm.tick_session()
        self.shm.tick_session()
        reval = self.shm.get_revalidation_required()
        self.assertIn("Mean_Reversion", reval)
        # Timestamp must not change after extra ticks
        self.assertEqual(self.shm._records["Mean_Reversion"].revalidation_timestamp, ts1)


# â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•
# G-002 Tests â€” Synthetic vs Live Divergence
# â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•

class TestG002DivergenceDetector(unittest.TestCase):

    def setUp(self):
        self.tmpdir = tempfile.mkdtemp()

    def test_gr008_divergence_creates_investigation(self):
        """GR-008: Material WR divergence (36pp) creates a RESEARCH_REQUIRED record."""
        det = _make_detector(self.tmpdir)
        created = det.check_divergence(
            strategy_name   = "Mean_Reversion",
            live_wr         = 0.22,
            live_n          = 9,
            live_avg_r      = -0.188,
            synthetic_wr    = 0.58,
            synthetic_avg_r = 0.00715,
        )
        self.assertTrue(created)
        pending = det.get_pending_investigations()
        self.assertEqual(len(pending), 1)
        self.assertEqual(pending[0].status, STATUS_RESEARCH_REQUIRED)
        self.assertGreater(pending[0].wr_divergence, 0.15)

    def test_gr009_no_duplicate_investigations(self):
        """GR-009: Second check_divergence for open investigation is a no-op."""
        det = _make_detector(self.tmpdir)
        det.check_divergence("Mean_Reversion", 0.22, 9, -0.188, 0.58, 0.007)
        created_again = det.check_divergence("Mean_Reversion", 0.22, 9, -0.188, 0.58, 0.007)
        self.assertFalse(created_again)
        self.assertEqual(len(det.get_pending_investigations()), 1)

    def test_gr009b_insufficient_sample_skips_divergence(self):
        """GR-009b: Below min_live_sample â†’ no investigation created."""
        det = _make_detector(self.tmpdir, min_live_sample=10)
        created = det.check_divergence("Mean_Reversion", 0.22, 5, -0.188, 0.58, 0.007)
        self.assertFalse(created)
        self.assertEqual(len(det.get_pending_investigations()), 0)

    def test_gr009c_no_divergence_below_threshold(self):
        """GR-009c: Small WR gap below 15pp threshold â†’ no investigation."""
        det = _make_detector(self.tmpdir, min_wr_divergence=0.15, min_expectancy_divergence=0.30)
        created = det.check_divergence("Mean_Reversion", 0.53, 15, 0.10, 0.58, 0.20)
        self.assertFalse(created)


# â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•
# G-003 Tests â€” Evolved Variant Governance
# â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•

class TestG003EvolvedVariantRouting(unittest.TestCase):

    def _make_sg_instance(self, extra_params: dict | None = None):
        """Build a StrategyGeneratorAI-like object just for _best_evolved_variant
        and _log_evolved_variant_audit, without needing heavy imports."""
        from strategy_lab.strategy_generator_ai import StrategyGeneratorAI, STRATEGY_PARAMS
        # Save and restore STRATEGY_PARAMS around each test
        original = dict(STRATEGY_PARAMS)
        if extra_params:
            STRATEGY_PARAMS.update(extra_params)
        sg = object.__new__(StrategyGeneratorAI)
        sg._meta = None
        return sg, STRATEGY_PARAMS, original

    def test_gr010_audit_log_when_base_excluded_no_variants(self):
        """GR-010: _log_evolved_variant_audit logs NO_VARIANTS_REGISTERED."""
        import strategy_lab.strategy_generator_ai as _sg_mod
        from strategy_lab.strategy_generator_ai import StrategyGeneratorAI, STRATEGY_PARAMS
        original = dict(STRATEGY_PARAMS)
        # Remove any Mean_Reversion variant
        for k in list(STRATEGY_PARAMS.keys()):
            if "Mean_Reversion" in k and k != "Mean_Reversion":
                del STRATEGY_PARAMS[k]
        try:
            sg = object.__new__(StrategyGeneratorAI)
            sg._meta = None
            mock_log = MagicMock()
            with patch.object(_sg_mod, "log", mock_log):
                sg._log_evolved_variant_audit("Mean_Reversion", set(), 2.5, "TEST")
            calls = str(mock_log.info.call_args_list)
            self.assertIn("NO_VARIANTS_REGISTERED", calls)
        finally:
            STRATEGY_PARAMS.clear()
            STRATEGY_PARAMS.update(original)

    def test_gr011_evolved_variant_selected_when_in_active(self):
        """GR-011: Variant selected when base excluded but variant in active."""
        from strategy_lab.strategy_generator_ai import StrategyGeneratorAI, STRATEGY_PARAMS
        original = dict(STRATEGY_PARAMS)
        STRATEGY_PARAMS["Mean_Reversion_Test_Variant"] = {
            "base_strategy": "Mean_Reversion",
            "min_rr": 2.0,
            "max_loss_pct": 0.01,
        }
        try:
            sg = object.__new__(StrategyGeneratorAI)
            sg._meta = None
            active = {"Mean_Reversion_Test_Variant", "Iron_Condor_Range"}
            result = sg._best_evolved_variant("Mean_Reversion", active, min_signal_rr=2.5)
            self.assertEqual(result, "Mean_Reversion_Test_Variant")
        finally:
            STRATEGY_PARAMS.clear()
            STRATEGY_PARAMS.update(original)

    def test_gr011b_variant_not_selected_when_rr_too_low(self):
        """GR-011b: Variant not selected when signal RR < variant min_rr."""
        from strategy_lab.strategy_generator_ai import StrategyGeneratorAI, STRATEGY_PARAMS
        original = dict(STRATEGY_PARAMS)
        STRATEGY_PARAMS["Mean_Reversion_Test_Variant"] = {
            "base_strategy": "Mean_Reversion",
            "min_rr": 2.0,
            "max_loss_pct": 0.01,
        }
        try:
            sg = object.__new__(StrategyGeneratorAI)
            sg._meta = None
            active = {"Mean_Reversion_Test_Variant", "Iron_Condor_Range"}
            result = sg._best_evolved_variant("Mean_Reversion", active, min_signal_rr=0.6)
            self.assertEqual(result, "")
        finally:
            STRATEGY_PARAMS.clear()
            STRATEGY_PARAMS.update(original)


# â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•
# G-004 Tests â€” Regime-Tagged Performance
# â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•

class TestG004RegimeMetadata(unittest.TestCase):

    def setUp(self):
        self.tmpdir = tempfile.mkdtemp()
        self.shm = _make_shm(self.tmpdir)

    def test_gr012_regime_metadata_attached_to_trades(self):
        """GR-012: regime parameter stored in trade_regime_counts."""
        self.shm.record_trade("Mean_Reversion", 0.02, 1.0, regime="range_market")
        self.shm.record_trade("Mean_Reversion", 0.01, 0.8, regime="range_market")
        self.shm.record_trade("Mean_Reversion", -0.01, -0.5, regime="bull_trend")
        rec = self.shm._records["Mean_Reversion"]
        self.assertEqual(rec.trade_regime_counts.get("range_market"), 2)
        self.assertEqual(rec.trade_regime_counts.get("bull_trend"), 1)
        regimes = [t["regime"] for t in rec.recent_trades_with_regime]
        self.assertIn("range_market", regimes)
        self.assertIn("bull_trend", regimes)

    def test_gr012b_regime_none_does_not_corrupt_counts(self):
        """GR-012b: record_trade with regime=None leaves trade_regime_counts unchanged."""
        self.shm.record_trade("Mean_Reversion", 0.01, 0.5)
        self.shm.record_trade("Mean_Reversion", 0.01, 0.5, regime=None)
        rec = self.shm._records["Mean_Reversion"]
        self.assertEqual(rec.trade_regime_counts, {})
        self.assertEqual(rec.recent_trades_with_regime, [])

    def test_gr012c_regime_counts_survive_serialization(self):
        """GR-012c: Regime counts survive to_dict/from_dict round-trip."""
        self.shm.record_trade("Mean_Reversion", 0.02, 1.0, regime="range_market")
        self.shm.record_trade("Mean_Reversion", -0.01, -0.5, regime="volatile")
        rec = self.shm._records["Mean_Reversion"]
        d = rec.to_dict()
        rec2 = StrategyHealthRecord.from_dict(d)
        self.assertEqual(rec2.trade_regime_counts.get("range_market"), 1)
        self.assertEqual(rec2.trade_regime_counts.get("volatile"), 1)
        self.assertEqual(len(rec2.recent_trades_with_regime), 2)


# â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•
# Safety / Invariant Tests
# â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•

class TestGovernanceSafetyInvariants(unittest.TestCase):

    def setUp(self):
        self.tmpdir = tempfile.mkdtemp()
        self.shm = _make_shm(self.tmpdir)

    def test_gr013_disabled_strategies_stay_disabled_after_governance_tick(self):
        """GR-013: disabled strategies remain blocked through all governance operations."""
        for _ in range(9):
            self.shm.record_trade("Mean_Reversion", -0.02, -1.0)
        self.assertIn("Mean_Reversion", self.shm.get_disabled_strategies())
        for _ in range(EARLY_ABORT_COOLDOWN):
            self.shm.tick_session()
        self.shm.mark_revalidation_complete("Mean_Reversion", "PASS", "test")
        self.assertIn("Mean_Reversion", self.shm.get_disabled_strategies(),
                      "PASS result alone must not re-enable the strategy")

    def test_gr014_no_trading_calls_from_governance_modules(self):
        """GR-014: Divergence detector and SHM revalidation produce zero live orders."""
        # PerformanceDivergenceDetector should not have any order-placement interface
        det = _make_detector(self.tmpdir)
        self.assertFalse(hasattr(det, "place_order"))
        self.assertFalse(hasattr(det, "submit_order"))
        self.assertFalse(hasattr(det, "execute_trade"))
        # SHM mark_revalidation_complete must not enable strategy (thus no signal route)
        for _ in range(9):
            self.shm.record_trade("Mean_Reversion", -0.02, -1.0)
        for _ in range(EARLY_ABORT_COOLDOWN):
            self.shm.tick_session()
        self.shm.mark_revalidation_complete("Mean_Reversion", "PASS", "test")
        # After all governance operations, strategy still disabled â†’ no signals possible
        self.assertIn("Mean_Reversion", self.shm.get_disabled_strategies())


if __name__ == "__main__":
    unittest.main(verbosity=2)

