"""
mop_rc001_observer.py — MOP-RC-001: Expected Move Observational Telemetry

PURPOSE
-------
Write date-partitioned, append-only JSON observation records for every signal
generated by EquityScannerAI.  Records are research-only artefacts: they are
NEVER read back into the trading pipeline and have zero effect on signal
selection, capital allocation, or execution.

OUTPUT
------
  data/mop_rc001/MOP_RC001_YYYY-MM-DD.json  — one JSON line per signal per call
  data/mop_rc001/MOP_RC001_YYYY-MM-DD.md    — daily markdown summary (on demand)

CONTRACT
--------
• All public functions silently swallow every exception — they NEVER raise.
• record_signal_observation() is idempotent within a Python session:
  duplicate calls for the same signal (same symbol + rounded_entry + date)
  are silently skipped.
• Files are created on first write; directories are created automatically.
• No imports from the trading pipeline — pure stdlib only.
"""
from __future__ import annotations

import json
import os
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Dict, Optional, Set

# ── Constants ────────────────────────────────────────────────────────────────
_DATA_DIR = Path(__file__).parent.parent / "data" / "mop_rc001"
_OBS_HORIZON_DAYS = 1   # observation horizon: 1 trading day (for future fill-in)

# ── Session-scoped dedup set ─────────────────────────────────────────────────
# Key: "<symbol>|<date>|<entry_price_rounded_cents>" — dedups within a session.
# Cleared at container restart, which is acceptable (restart = new session).
_SEEN_THIS_SESSION: Set[str] = set()


def _get_output_path(date_str: str) -> Path:
    """Return the JSONL output path for the given date string (YYYY-MM-DD)."""
    return _DATA_DIR / f"MOP_RC001_{date_str}.json"


def record_signal_observation(
    sig: Any,
    candidate: Dict[str, Any],
) -> None:
    """
    Append one JSON observation record to today's JSONL file.

    Parameters
    ----------
    sig       : TradeSignal — the accepted signal from EquityScannerAI.scan()
    candidate : dict row from the watchlist (stock dict) — provides rsi, vol_ratio, score.

    This function NEVER raises.  If anything fails, it logs nothing and returns.
    All signal fields are read; no field is written back to ``sig``.
    """
    try:
        _record_impl(sig, candidate)
    except Exception:
        pass  # observation failure must never affect signal flow


def _record_impl(sig: Any, candidate: Dict[str, Any]) -> None:
    """Internal implementation — called only from record_signal_observation()."""
    # ── Build dedup key ───────────────────────────────────────────────────────
    now_utc   = datetime.now(timezone.utc)
    date_str  = now_utc.strftime("%Y-%m-%d")
    symbol    = (getattr(sig, "symbol", None) or "UNKNOWN").strip()
    entry_raw = float(getattr(sig, "entry_price", 0.0) or 0.0)
    # Round to nearest 5 paise to tolerate sub-tick noise between duplicate calls
    entry_key = round(entry_raw * 20) / 20.0
    dedup_key = f"{symbol}|{date_str}|{entry_key:.2f}"
    if dedup_key in _SEEN_THIS_SESSION:
        return   # duplicate — skip silently
    _SEEN_THIS_SESSION.add(dedup_key)

    # ── Extract signal fields ─────────────────────────────────────────────────
    atr       = float(getattr(sig, "atr", 0.0) or 0.0)
    direction = getattr(sig, "direction", None)
    dir_str   = getattr(direction, "value", str(direction)) if direction is not None else "UNKNOWN"
    target    = float(getattr(sig, "target_price",  0.0) or 0.0)
    stop      = float(getattr(sig, "stop_loss",     0.0) or 0.0)
    conf      = float(getattr(sig, "confidence",    0.0) or 0.0)
    strategy  = str(getattr(sig, "strategy_name",   "unassigned") or "unassigned")
    emp       = getattr(sig, "expected_move_pct",   None)
    c_score   = getattr(sig, "_obs_candidate_score",None)
    regime    = getattr(sig, "_obs_regime",          None)

    # Compute RR from signal fields (avoids calling the property; handles edge cases)
    rr: Optional[float] = None
    if entry_raw and stop and entry_raw != stop and target:
        try:
            rr = round(abs(target - entry_raw) / abs(entry_raw - stop), 4)
        except ZeroDivisionError:
            rr = None

    # ATR% for quick cross-signal comparison
    atr_pct: Optional[float] = None
    if atr and entry_raw and entry_raw > 0:
        atr_pct = round(atr / entry_raw * 100, 4)

    # Candidate features (scanner-side context)
    rsi       = candidate.get("rsi")
    vol_ratio = candidate.get("volume_ratio")
    sector    = candidate.get("sector", "")

    # ── Build record ──────────────────────────────────────────────────────────
    ts_str = now_utc.strftime("%Y-%m-%dT%H:%M:%SZ")
    record: Dict[str, Any] = {
        "obs_id":              f"{symbol}_{now_utc.strftime('%H%M%S')}",
        "ts_utc":              ts_str,
        "trading_date":        date_str,
        "symbol":              symbol,
        "direction":           dir_str,
        "entry_price":         entry_raw,
        "stop_loss":           stop,
        "target_price":        target,
        "atr":                 atr,
        "atr_pct":             atr_pct,
        "rr":                  rr,
        "expected_move_pct":   emp,
        "confidence":          conf,
        "candidate_score":     c_score,
        "strategy":            strategy,
        "regime":              regime,
        "rsi":                 rsi,
        "vol_ratio":           vol_ratio,
        "sector":              sector,
        "observation_horizon_days": _OBS_HORIZON_DAYS,
        # Outcome fields — filled by post-hoc analysis after the trading day
        "selected":            None,  # did the signal reach CRE approval?
        "actual_return_pct":   None,  # actual 1-day price move (%)
        "no_lookahead":        True,  # assertion: no future data used here
    }

    # ── Write to JSONL file ───────────────────────────────────────────────────
    _DATA_DIR.mkdir(parents=True, exist_ok=True)
    out_path = _get_output_path(date_str)
    with out_path.open("a", encoding="utf-8") as fh:
        fh.write(json.dumps(record, ensure_ascii=False))
        fh.write("\n")


def write_daily_summary_md(date_str: Optional[str] = None) -> Optional[Path]:
    """
    Produce a markdown summary of all observations recorded for ``date_str``
    (defaults to today).  Returns the output path, or None on any error.
    This function NEVER raises.
    """
    try:
        return _summary_impl(date_str)
    except Exception:
        return None


def _summary_impl(date_str: Optional[str]) -> Optional[Path]:
    """Internal markdown summary generator."""
    if date_str is None:
        date_str = datetime.now(timezone.utc).strftime("%Y-%m-%d")

    json_path = _get_output_path(date_str)
    if not json_path.exists():
        return None

    records = []
    with json_path.open("r", encoding="utf-8") as fh:
        for line in fh:
            line = line.strip()
            if line:
                try:
                    records.append(json.loads(line))
                except Exception:
                    continue

    if not records:
        return None

    # Compute summary statistics
    n = len(records)
    longs  = sum(1 for r in records if r.get("direction") in ("BUY", "LONG"))
    shorts = n - longs
    emps   = [r["expected_move_pct"] for r in records if r.get("expected_move_pct") is not None]
    rrs    = [r["rr"]                for r in records if r.get("rr") is not None]
    confs  = [r["confidence"]        for r in records if r.get("confidence") is not None]

    def _fmt(vals: list) -> str:
        if not vals:
            return "N/A"
        return f"min={min(vals):.2f}  avg={sum(vals)/len(vals):.2f}  max={max(vals):.2f}"

    strategy_counts: Dict[str, int] = {}
    regime_counts:   Dict[str, int] = {}
    for r in records:
        s = r.get("strategy", "unknown") or "unknown"
        rg = r.get("regime", "unknown") or "unknown"
        strategy_counts[s]  = strategy_counts.get(s, 0) + 1
        regime_counts[rg]   = regime_counts.get(rg, 0) + 1

    lines = [
        f"# MOP-RC-001 Daily Observation Summary — {date_str}",
        "",
        f"**Signals observed:** {n}  |  **LONG:** {longs}  |  **SHORT:** {shorts}",
        "",
        "## expected_move_pct distribution",
        f"  {_fmt(emps)}  (n={len(emps)})",
        "",
        "## risk_reward distribution",
        f"  {_fmt(rrs)}  (n={len(rrs)})",
        "",
        "## confidence distribution",
        f"  {_fmt(confs)}  (n={len(confs)})",
        "",
        "## Strategy breakdown",
    ]
    for strat, cnt in sorted(strategy_counts.items(), key=lambda x: -x[1]):
        lines.append(f"  - {strat}: {cnt}")
    lines += ["", "## Regime breakdown"]
    for rg, cnt in sorted(regime_counts.items(), key=lambda x: -x[1]):
        lines.append(f"  - {rg}: {cnt}")
    lines += [
        "",
        "## Selected / outcome fill-in",
        "  `selected` and `actual_return_pct` are `null` at signal time.",
        "  Run the post-hoc analysis script after market close to populate.",
        "",
        f"*Generated: {datetime.now(timezone.utc).strftime('%Y-%m-%dT%H:%M:%SZ')}*",
    ]

    md_path = _DATA_DIR / f"MOP_RC001_{date_str}.md"
    md_path.write_text("\n".join(lines), encoding="utf-8")
    return md_path


def load_observations(date_str: Optional[str] = None) -> list:
    """
    Return all observation records for the given date as a list of dicts.
    Returns [] if the file doesn't exist or on any error.
    Never raises.
    """
    try:
        if date_str is None:
            date_str = datetime.now(timezone.utc).strftime("%Y-%m-%d")
        path = _get_output_path(date_str)
        if not path.exists():
            return []
        records = []
        with path.open("r", encoding="utf-8") as fh:
            for line in fh:
                line = line.strip()
                if line:
                    try:
                        records.append(json.loads(line))
                    except Exception:
                        continue
        return records
    except Exception:
        return []
