"""
iios/knowledge/knowledge_constants.py
======================================
All enumerations, numeric limits, and string constants for the
IIOS Knowledge Engine.
"""

from __future__ import annotations

from enum import Enum
from typing import Final

__all__ = [
    # Knowledge types
    "KnowledgeType",
    "KnowledgeStatus",
    "KnowledgePriority",
    "KnowledgeSource",
    "KnowledgeDomain",
    # Versioning
    "VersionBump",
    "VersionStatus",
    # Validation
    "ValidationResult",
    "ConstraintType",
    # Query
    "QueryOperator",
    "SortOrder",
    "SearchMode",
    # Relationship
    "RelationshipType",
    "RelationshipStrength",
    # Index
    "IndexType",
    # Lifecycle events
    "KnowledgeEvent",
    # Numeric defaults
    "DEFAULT_PAGE_SIZE",
    "MAX_PAGE_SIZE",
    "DEFAULT_CACHE_TTL",
    "MAX_TAGS",
    "MAX_RELATIONSHIPS",
    "MAX_SNAPSHOT_HISTORY",
    "MAX_KEYWORD_LENGTH",
    "MAX_SEARCH_RESULTS",
    "DEFAULT_CONFIDENCE",
    "MIN_CONFIDENCE",
    "MAX_CONFIDENCE",
    "DEFAULT_TTL_SECONDS",
    "SCHEMA_VERSION",
    # String constants
    "KNOWLEDGE_NAMESPACE",
    "SYSTEM_OWNER",
    "ANONYMOUS_OWNER",
]


# ── Knowledge types ────────────────────────────────────────────────────────────

class KnowledgeType(str, Enum):
    """Broad category of a knowledge item."""
    FACT        = "fact"         # Verified datum (price, rate, threshold)
    RULE        = "rule"         # Business rule, policy
    CONCEPT     = "concept"      # Domain concept, definition
    PATTERN     = "pattern"      # Market/behavioural pattern
    STRATEGY    = "strategy"     # Trading strategy descriptor
    SIGNAL      = "signal"       # Trade signal or indicator
    EVENT       = "event"        # Historical market or system event
    OBSERVATION = "observation"  # Raw observation awaiting analysis
    INFERENCE   = "inference"    # Derived/inferred knowledge
    MODEL       = "model"        # ML/statistical model descriptor
    METRIC      = "metric"       # Performance / health metric
    ONTOLOGY    = "ontology"     # Ontology definition node
    PROCEDURE   = "procedure"    # SOP, workflow step
    CONSTRAINT  = "constraint"   # Hard limit / boundary
    UNKNOWN     = "unknown"


class KnowledgeStatus(str, Enum):
    """Lifecycle status of a knowledge item."""
    DRAFT       = "draft"        # Being authored, not yet active
    ACTIVE      = "active"       # In use by the system
    DEPRECATED  = "deprecated"   # No longer recommended, kept for history
    ARCHIVED    = "archived"     # Removed from active use, cold storage
    PENDING     = "pending"      # Awaiting validation/approval
    INVALID     = "invalid"      # Failed validation
    SUPERSEDED  = "superseded"   # Replaced by a newer version


class KnowledgePriority(int, Enum):
    """Importance ordering for knowledge items."""
    CRITICAL = 5
    HIGH     = 4
    MEDIUM   = 3
    LOW      = 2
    MINIMAL  = 1


class KnowledgeSource(str, Enum):
    """Origin of a knowledge item."""
    SYSTEM      = "system"       # Auto-generated by IIOS
    USER        = "user"         # Manually created
    AGENT       = "agent"        # Created by an AI agent
    LEARNED     = "learned"      # Emerged from ML learning
    EXTERNAL    = "external"     # Imported from external data feed
    DERIVED     = "derived"      # Computed from other knowledge
    VALIDATED   = "validated"    # Externally validated


class KnowledgeDomain(str, Enum):
    """Business domain the knowledge belongs to."""
    MARKET      = "market"       # Market data & conditions
    TRADING     = "trading"      # Trade execution & strategy
    RISK        = "risk"         # Risk management
    PORTFOLIO   = "portfolio"    # Portfolio management
    RESEARCH    = "research"     # Research & analysis
    OPERATIONS  = "operations"   # Ops & infrastructure
    COMPLIANCE  = "compliance"   # Regulatory compliance
    SYSTEM      = "system"       # Internal system knowledge
    GENERAL     = "general"


# ── Versioning ─────────────────────────────────────────────────────────────────

class VersionBump(str, Enum):
    """Type of version increment."""
    MAJOR = "major"   # Breaking change
    MINOR = "minor"   # Backward-compatible addition
    PATCH = "patch"   # Small fix / metadata only
    SNAPSHOT = "snapshot"  # Non-version checkpoint


class VersionStatus(str, Enum):
    """Status of a specific version."""
    CURRENT    = "current"
    HISTORICAL = "historical"
    SNAPSHOT   = "snapshot"
    ROLLBACK   = "rollback"


# ── Validation ─────────────────────────────────────────────────────────────────

class ValidationResult(str, Enum):
    PASS    = "pass"
    FAIL    = "fail"
    WARNING = "warning"
    SKIP    = "skip"


class ConstraintType(str, Enum):
    REQUIRED     = "required"
    TYPE         = "type"
    RANGE        = "range"
    PATTERN      = "pattern_match"
    UNIQUE       = "unique"
    RELATIONSHIP = "relationship"
    CUSTOM       = "custom"


# ── Query ──────────────────────────────────────────────────────────────────────

class QueryOperator(str, Enum):
    EQ          = "eq"
    NEQ         = "neq"
    GT          = "gt"
    GTE         = "gte"
    LT          = "lt"
    LTE         = "lte"
    IN          = "in"
    NOT_IN      = "not_in"
    CONTAINS    = "contains"
    STARTS_WITH = "starts_with"
    ENDS_WITH   = "ends_with"
    EXISTS      = "exists"
    BETWEEN     = "between"


class SortOrder(str, Enum):
    ASC  = "asc"
    DESC = "desc"


class SearchMode(str, Enum):
    EXACT    = "exact"
    KEYWORD  = "keyword"
    FUZZY    = "fuzzy"
    SEMANTIC = "semantic"
    HYBRID   = "hybrid"


# ── Relationships ──────────────────────────────────────────────────────────────

class RelationshipType(str, Enum):
    DEPENDS_ON    = "depends_on"
    RELATED_TO    = "related_to"
    EXTENDS       = "extends"
    IMPLEMENTS    = "implements"
    CONTRADICTS   = "contradicts"
    SUPPORTS      = "supports"
    SUPERSEDES    = "supersedes"
    DERIVED_FROM  = "derived_from"
    PART_OF       = "part_of"
    APPLIES_TO    = "applies_to"
    TRIGGERS      = "triggers"
    INVALIDATES   = "invalidates"


class RelationshipStrength(float, Enum):
    STRONG   = 1.0
    MODERATE = 0.6
    WEAK     = 0.3
    UNKNOWN  = 0.0


# ── Index ──────────────────────────────────────────────────────────────────────

class IndexType(str, Enum):
    ID        = "id"
    TAG       = "tag"
    KEYWORD   = "keyword"
    METADATA  = "metadata"
    DOMAIN    = "domain"
    TYPE      = "type"
    OWNER     = "owner"
    STATUS    = "status"
    TIMESTAMP = "timestamp"


# ── Lifecycle Events ───────────────────────────────────────────────────────────

class KnowledgeEvent(str, Enum):
    CREATED     = "knowledge.created"
    UPDATED     = "knowledge.updated"
    DELETED     = "knowledge.deleted"
    VALIDATED   = "knowledge.validated"
    INVALIDATED = "knowledge.invalidated"
    VERSIONED   = "knowledge.versioned"
    ARCHIVED    = "knowledge.archived"
    RESTORED    = "knowledge.restored"
    SEARCHED    = "knowledge.searched"
    LINKED      = "knowledge.linked"
    UNLINKED    = "knowledge.unlinked"


# ── Numeric defaults ───────────────────────────────────────────────────────────

DEFAULT_PAGE_SIZE:    Final[int]   = 20
MAX_PAGE_SIZE:        Final[int]   = 500
DEFAULT_CACHE_TTL:    Final[int]   = 300          # 5 minutes
MAX_TAGS:             Final[int]   = 50
MAX_RELATIONSHIPS:    Final[int]   = 1_000
MAX_SNAPSHOT_HISTORY: Final[int]   = 100
MAX_KEYWORD_LENGTH:   Final[int]   = 256
MAX_SEARCH_RESULTS:   Final[int]   = 1_000
DEFAULT_CONFIDENCE:   Final[float] = 1.0
MIN_CONFIDENCE:       Final[float] = 0.0
MAX_CONFIDENCE:       Final[float] = 1.0
DEFAULT_TTL_SECONDS:  Final[int]   = 0            # 0 = never expires
SCHEMA_VERSION:       Final[str]   = "1.0.0"

# ── String constants ───────────────────────────────────────────────────────────

KNOWLEDGE_NAMESPACE: Final[str] = "iios.knowledge"
SYSTEM_OWNER:        Final[str] = "iios:system"
ANONYMOUS_OWNER:     Final[str] = "iios:anonymous"
