"""
iios/execution/analytics/predictive/predictive_response.py
==========================================================
Output types for the Institutional Predictive Intelligence Framework:

  - ForecastPoint
  - Forecast
  - ProbabilityReport
  - CapacityForecast
  - RiskForecast
  - OperationalForecast
  - ForecastSummary
  - PredictiveSnapshot
  - PredictionReport

C8 Execution Analytics & Intelligence — Phase 1, Module 4
"""
from __future__ import annotations

import time
import uuid
from dataclasses import dataclass, field
from typing import Any, Dict, List, Optional, Tuple

from .constants import (
    VERSION,
    ConfidenceLevel,
    ForecastHorizon,
    PredictionDomain,
    PredictionType,
    RiskLevel,
    TrendType,
    confidence_to_level,
    risk_score_to_level,
)


# ── ForecastPoint ─────────────────────────────────────────────────────────────

@dataclass(frozen=True)
class ForecastPoint:
    """A single predicted value at a specific time offset."""

    step:           int     # 1..DEFAULT_FORECAST_POINTS
    offset_seconds: float   # seconds ahead of now
    value:          float
    lower_bound:    float
    upper_bound:    float
    confidence:     float   # [0, 1]

    def to_dict(self) -> Dict[str, Any]:
        return {
            "step":           self.step,
            "offset_seconds": self.offset_seconds,
            "value":          self.value,
            "lower_bound":    self.lower_bound,
            "upper_bound":    self.upper_bound,
            "confidence":     self.confidence,
        }


# ── Forecast ──────────────────────────────────────────────────────────────────

@dataclass(frozen=True)
class Forecast:
    """
    Immutable operational forecast for a single PredictionType.

    Generated by PredictiveForecaster.
    """

    forecast_id:       str
    prediction_type:   PredictionType
    domain:            PredictionDomain
    horizon:           ForecastHorizon
    forecast_points:   Tuple[ForecastPoint, ...]   = field(default_factory=tuple)
    trend:             TrendType                   = TrendType.UNKNOWN
    confidence:        float                       = 0.0
    horizon_seconds:   float                       = 0.0
    data_points_used:  int                         = 0
    algorithm:         str                         = "linear"
    generated_at:      float                       = field(default_factory=time.time)
    version:           str                         = VERSION

    @property
    def confidence_level(self) -> ConfidenceLevel:
        return confidence_to_level(self.confidence)

    @property
    def terminal_forecast(self) -> float:
        """Value at the end of the forecast horizon."""
        if not self.forecast_points:
            return 0.0
        return self.forecast_points[-1].value

    @property
    def point_count(self) -> int:
        return len(self.forecast_points)

    def to_dict(self) -> Dict[str, Any]:
        return {
            "forecast_id":      self.forecast_id,
            "prediction_type":  self.prediction_type.value,
            "domain":           self.domain.value,
            "horizon":          self.horizon.value,
            "trend":            self.trend.value,
            "confidence":       self.confidence,
            "confidence_level": self.confidence_level.value,
            "terminal_forecast":self.terminal_forecast,
            "point_count":      self.point_count,
            "data_points_used": self.data_points_used,
            "algorithm":        self.algorithm,
            "generated_at":     self.generated_at,
        }


# ── ProbabilityReport ─────────────────────────────────────────────────────────

@dataclass(frozen=True)
class ProbabilityReport:
    """
    Immutable probability estimates for prediction types.
    """

    report_id:        str
    domain:           PredictionDomain
    horizon:          ForecastHorizon
    probabilities:    Dict[str, float]        = field(default_factory=dict, compare=False)
    confidence_scores: Dict[str, float]       = field(default_factory=dict, compare=False)
    generated_at:     float                   = field(default_factory=time.time)
    version:          str                     = VERSION

    def get(self, prediction_type: PredictionType) -> float:
        return self.probabilities.get(prediction_type.value, 0.0)

    def to_dict(self) -> Dict[str, Any]:
        return {
            "report_id":        self.report_id,
            "domain":           self.domain.value,
            "horizon":          self.horizon.value,
            "probabilities":    dict(self.probabilities),
            "confidence_scores":dict(self.confidence_scores),
            "generated_at":     self.generated_at,
        }


# ── CapacityForecast ──────────────────────────────────────────────────────────

@dataclass(frozen=True)
class CapacityForecast:
    """
    Immutable capacity forecast for a domain.
    """

    capacity_id:              str
    domain:                   PredictionDomain
    horizon:                  ForecastHorizon
    current_utilization:      float               = 0.0
    forecasted_utilization:   float               = 0.0
    capacity_headroom:        float               = 1.0   # 1 - forecasted_utilization
    bottleneck_risk:          float               = 0.0   # [0, 1]
    risk_level:               RiskLevel           = RiskLevel.MINIMAL
    confidence:               float               = 0.0
    generated_at:             float               = field(default_factory=time.time)
    version:                  str                 = VERSION

    def to_dict(self) -> Dict[str, Any]:
        return {
            "capacity_id":             self.capacity_id,
            "domain":                  self.domain.value,
            "horizon":                 self.horizon.value,
            "current_utilization":     self.current_utilization,
            "forecasted_utilization":  self.forecasted_utilization,
            "capacity_headroom":       self.capacity_headroom,
            "bottleneck_risk":         self.bottleneck_risk,
            "risk_level":              self.risk_level.value,
            "confidence":              self.confidence,
            "generated_at":            self.generated_at,
        }


# ── RiskForecast ──────────────────────────────────────────────────────────────

@dataclass(frozen=True)
class RiskForecast:
    """
    Immutable operational risk forecast for a domain.
    """

    risk_id:               str
    domain:                PredictionDomain
    horizon:               ForecastHorizon
    risk_level:            RiskLevel              = RiskLevel.MINIMAL
    risk_score:            float                  = 0.0
    contributing_factors:  Tuple[str, ...]         = field(default_factory=tuple)
    mitigation_indicators: Tuple[str, ...]         = field(default_factory=tuple)
    confidence:            float                   = 0.0
    generated_at:          float                   = field(default_factory=time.time)
    version:               str                     = VERSION

    def to_dict(self) -> Dict[str, Any]:
        return {
            "risk_id":               self.risk_id,
            "domain":                self.domain.value,
            "horizon":               self.horizon.value,
            "risk_level":            self.risk_level.value,
            "risk_score":            self.risk_score,
            "contributing_factors":  list(self.contributing_factors),
            "mitigation_indicators": list(self.mitigation_indicators),
            "confidence":            self.confidence,
            "generated_at":          self.generated_at,
        }


# ── OperationalForecast ───────────────────────────────────────────────────────

@dataclass(frozen=True)
class OperationalForecast:
    """
    Immutable operational health and availability forecast.
    """

    operational_id:      str
    domain:              PredictionDomain
    horizon:             ForecastHorizon
    health_score:        float             = 0.0
    availability_forecast: float          = 1.0
    performance_outlook: TrendType        = TrendType.UNKNOWN
    overall_confidence:  float            = 0.0
    generated_at:        float            = field(default_factory=time.time)
    version:             str              = VERSION

    def to_dict(self) -> Dict[str, Any]:
        return {
            "operational_id":       self.operational_id,
            "domain":               self.domain.value,
            "horizon":              self.horizon.value,
            "health_score":         self.health_score,
            "availability_forecast":self.availability_forecast,
            "performance_outlook":  self.performance_outlook.value,
            "overall_confidence":   self.overall_confidence,
            "generated_at":         self.generated_at,
        }


# ── ForecastSummary ───────────────────────────────────────────────────────────

@dataclass(frozen=True)
class ForecastSummary:
    """
    Immutable summary of all forecasts in a prediction cycle.
    """

    summary_id:           str
    domain:               PredictionDomain
    horizon:              ForecastHorizon
    total_forecasts:      int             = 0
    avg_confidence:       float           = 0.0
    dominant_trend:       TrendType       = TrendType.UNKNOWN
    high_confidence_count:int             = 0
    low_confidence_count: int             = 0
    generated_at:         float           = field(default_factory=time.time)
    version:              str             = VERSION

    def to_dict(self) -> Dict[str, Any]:
        return {
            "summary_id":            self.summary_id,
            "domain":                self.domain.value,
            "horizon":               self.horizon.value,
            "total_forecasts":       self.total_forecasts,
            "avg_confidence":        self.avg_confidence,
            "dominant_trend":        self.dominant_trend.value,
            "high_confidence_count": self.high_confidence_count,
            "low_confidence_count":  self.low_confidence_count,
            "generated_at":          self.generated_at,
        }


# ── PredictiveSnapshot ────────────────────────────────────────────────────────

@dataclass(frozen=True)
class PredictiveSnapshot:
    """
    Immutable point-in-time snapshot of all active forecasts.
    """

    snapshot_id:  str
    domain:       PredictionDomain
    horizon:      ForecastHorizon
    forecasts:    Tuple[Forecast, ...]   = field(default_factory=tuple)
    captured_at:  float                  = field(default_factory=time.time)
    version:      str                    = VERSION

    @property
    def forecast_count(self) -> int:
        return len(self.forecasts)

    def to_dict(self) -> Dict[str, Any]:
        return {
            "snapshot_id":    self.snapshot_id,
            "domain":         self.domain.value,
            "horizon":        self.horizon.value,
            "forecast_count": self.forecast_count,
            "captured_at":    self.captured_at,
            "version":        self.version,
        }


# ── PredictionReport ──────────────────────────────────────────────────────────

@dataclass(frozen=True)
class PredictionReport:
    """
    Immutable full prediction report — the primary output of the
    Predictive Intelligence Framework.

    Returned by PredictiveIntelligenceEngine.process().
    """

    report_id:            str
    request_id:           str
    domain:               PredictionDomain
    horizon:              ForecastHorizon
    forecasts:            Tuple[Forecast, ...]
    snapshot:             PredictiveSnapshot
    probability_report:   Optional[ProbabilityReport]   = None
    capacity_forecast:    Optional[CapacityForecast]    = None
    risk_forecast:        Optional[RiskForecast]        = None
    operational_forecast: Optional[OperationalForecast] = None
    forecast_summary:     Optional[ForecastSummary]     = None
    error_message:        str                           = ""
    processing_ms:        float                         = 0.0
    generated_at:         float                         = field(default_factory=time.time)
    version:              str                           = VERSION

    @property
    def is_success(self) -> bool:
        return not self.error_message

    @property
    def forecast_count(self) -> int:
        return len(self.forecasts)

    def to_dict(self) -> Dict[str, Any]:
        return {
            "report_id":           self.report_id,
            "request_id":          self.request_id,
            "domain":              self.domain.value,
            "horizon":             self.horizon.value,
            "forecast_count":      self.forecast_count,
            "has_probabilities":   self.probability_report is not None,
            "has_capacity":        self.capacity_forecast is not None,
            "has_risk":            self.risk_forecast is not None,
            "has_operational":     self.operational_forecast is not None,
            "has_summary":         self.forecast_summary is not None,
            "error_message":       self.error_message,
            "processing_ms":       self.processing_ms,
            "generated_at":        self.generated_at,
            "version":             self.version,
        }


# ── Factory helpers ───────────────────────────────────────────────────────────

def make_predictive_snapshot(
    domain:    PredictionDomain,
    horizon:   ForecastHorizon,
    forecasts: List[Forecast],
    *,
    snapshot_id: Optional[str] = None,
) -> PredictiveSnapshot:
    return PredictiveSnapshot(
        snapshot_id = snapshot_id or str(uuid.uuid4()),
        domain      = domain,
        horizon     = horizon,
        forecasts   = tuple(forecasts),
    )
