"""
Trade Signal Model
Represents a buy/sell/hedge signal generated by the Opportunity Engine or Strategy Lab.
"""

from __future__ import annotations
from dataclasses import dataclass, field
from datetime import datetime
from enum import Enum
from typing import Optional


class SignalDirection(str, Enum):
    BUY   = "BUY"
    SELL  = "SELL"
    SHORT = "SHORT"
    HEDGE = "HEDGE"
    EXIT  = "EXIT"


class SignalStrength(str, Enum):
    WEAK     = "weak"
    MODERATE = "moderate"
    STRONG   = "strong"


class SignalType(str, Enum):
    EQUITY   = "equity"
    OPTIONS  = "options"
    FUTURES  = "futures"
    SPREAD   = "spread"


@dataclass
class TradeSignal:
    """
    A fully described trade opportunity passed from the Opportunity Engine /
    Strategy Lab through the debate and decision layers to the Execution Engine.
    """
    symbol: str
    direction: SignalDirection
    signal_type: SignalType              = SignalType.EQUITY
    strength: SignalStrength             = SignalStrength.MODERATE
    entry_price: float                   = 0.0
    stop_loss: float                     = 0.0
    target_price: float                  = 0.0
    quantity: int                        = 0
    strategy_name: str                   = "unassigned"
    confidence: float                    = 0.0           # 0–10
    source_agent: str                    = ""
    timestamp: datetime                  = field(default_factory=datetime.now)
    expiry: Optional[datetime]           = None          # for options/futures
    strike_price: Optional[float]        = None
    option_type: Optional[str]           = None          # CE / PE
    notes: str                           = ""
    atr:   float                         = 0.0   # ATR(14) at signal creation; drives SL distance and zone width
    adv_crore: float                     = 0.0   # Average Daily Volume in ₹ crore; used by LiquidityGuard to cap position size
    entry_zone_low:  float               = 0.0   # entry − ATR(14)×0.10  — lower bound of acceptable entry zone
    entry_zone_high: float               = 0.0   # entry + ATR(14)×0.10  — upper bound of acceptable entry zone

    @property
    def risk_reward_ratio(self) -> float:
        if self.stop_loss == 0 or self.entry_price == 0:
            return 0.0
        risk   = abs(self.entry_price - self.stop_loss)
        reward = abs(self.target_price - self.entry_price)
        return reward / risk if risk else 0.0

    def summary(self) -> str:
        return (
            f"[Signal] {self.symbol} {self.direction.value} | "
            f"Entry: {self.entry_price:.2f} | SL: {self.stop_loss:.2f} | "
            f"Target: {self.target_price:.2f} | RR: {self.risk_reward_ratio:.1f} | "
            f"Confidence: {self.confidence:.1f} | Strategy: {self.strategy_name}"
        )
