"""
Edge Diagnostics Dashboard
===========================
Streamlit app that displays all edge analytics from the last replay run
in a single six-panel view.

Run:
    streamlit run simulation_replay/edge_dashboard.py

Data source:  data/replay_summary.json
Generated by: python simulation_replay/run_replay.py [--days N]

Panel layout:
    ┌─────────────────────────────────────────────────────┐
    │  Banner: last run · date range · replay days        │
    ├──────────────────────┬──────────────────────────────┤
    │  Panel 1             │  Panel 2                     │
    │  Core Performance    │  Market Capture Ratio        │
    ├──────────────────────┼──────────────────────────────┤
    │  Panel 3             │  Panel 4                     │
    │  Edge Half-Life      │  Edge Distribution Map       │
    ├──────────────────────┼──────────────────────────────┤
    │  Panel 5             │  Panel 6                     │
    │  Volatility Stability│  System Health & GO/NO-GO    │
    └──────────────────────┴──────────────────────────────┘
"""

from __future__ import annotations

import json
import math
from datetime import datetime
from pathlib import Path
from typing import Any, Dict, List, Optional

# ── Paths ─────────────────────────────────────────────────────────────────────
_ROOT        = Path(__file__).resolve().parent.parent
SUMMARY_PATH = _ROOT / "data" / "replay_summary.json"

# ── Streamlit guard ────────────────────────────────────────────────────────────
try:
    import streamlit as st
except ImportError:
    raise SystemExit("Streamlit not installed.  Run:  pip install streamlit>=1.32.0")

try:
    import pandas as pd
    HAS_PANDAS = True
except ImportError:
    HAS_PANDAS = False

# ── Page config (must be first Streamlit call) ────────────────────────────────
st.set_page_config(
    page_title="Edge Diagnostics Dashboard",
    page_icon="📊",
    layout="wide",
    initial_sidebar_state="collapsed",
)

# ── Helpers ────────────────────────────────────────────────────────────────────

@st.cache_data(ttl=30)
def _load_summary() -> Optional[Dict[str, Any]]:
    """Load replay_summary.json; return None if missing or corrupt."""
    if not SUMMARY_PATH.exists():
        return None
    try:
        return json.loads(SUMMARY_PATH.read_text(encoding="utf-8"))
    except Exception:
        return None


def _safe(d: Any, *keys, default=None) -> Any:
    """Safe nested dict get: _safe(d, 'a', 'b') == d.get('a',{}).get('b')."""
    for k in keys:
        if not isinstance(d, dict):
            return default
        d = d.get(k, default)
    return d


def _fmt_r(v) -> str:
    if v is None or (isinstance(v, float) and math.isnan(v)):
        return "n/a"
    return f"{v:+.3f}R"


def _fmt_pct(v) -> str:
    if v is None:
        return "—"
    return f"{v:.1f}%"


def _capture_label(cap) -> str:
    if cap is None:
        return "—"
    if cap >= 40:  return "DOMINANT"
    if cap >= 15:  return "MODERATE"
    if cap >= 0:   return "WEAK"
    return "NEGATIVE"


# ── Load data ─────────────────────────────────────────────────────────────────
data = _load_summary()

# ── Header banner ─────────────────────────────────────────────────────────────
st.markdown("# 📊 Edge Diagnostics Dashboard")
st.markdown("_Single-panel view of all edge analytics — run `simulation_replay/run_replay.py` to refresh._")

if data is None:
    st.error(
        "**`data/replay_summary.json` not found.**  "
        "Run the replay first to populate the dashboard."
    )
    st.code("python simulation_replay/run_replay.py --days 30", language="bash")
    st.stop()

# Banner metrics
gen_at  = data.get("generated_at", "")
gen_str = datetime.fromisoformat(gen_at).strftime("%Y-%m-%d  %H:%M") if gen_at else "—"

b1, b2, b3, b4 = st.columns(4)
b1.metric("Last Replay",    gen_str)
b2.metric("Days",           f"{data.get('days_replayed', '?')} / {data.get('target_days', '?')}")
b3.metric("Date Range",     data.get("date_range", "—"))
b4.metric("Run Duration",   f"{data.get('run_duration_sec', 0):.0f}s")

st.divider()

# ══════════════════════════════════════════════════════════════════════════════
# Row 1 — Core Performance  |  Market Capture Ratio
# ══════════════════════════════════════════════════════════════════════════════
col1, col2 = st.columns(2)

# ── Panel 1: Core Performance ─────────────────────────────────────────────────
with col1:
    st.subheader("Panel 1 — Core Performance")

    m       = data.get("metrics") or {}
    pf      = m.get("profit_factor")
    wr      = m.get("win_rate")
    avg_r   = m.get("avg_r_multiple")
    dd      = m.get("max_drawdown_pct")
    pnl     = m.get("total_pnl")
    n_trade = m.get("trades_executed", 0)
    n_sig   = m.get("total_signals", 0)
    appr    = m.get("trades_approved_pct", 0)

    # PF delta label
    pf_lbl = ("Excellent" if pf and pf >= 2.0
               else ("Good" if pf and pf >= 1.5
               else ("Acceptable" if pf and pf >= 1.0
               else "Below threshold")))

    r1c1, r1c2, r1c3 = st.columns(3)
    r1c1.metric("Profit Factor",   f"{pf:.2f}"  if pf  is not None else "—", delta=pf_lbl)
    r1c2.metric("Win Rate",        f"{wr:.1f}%" if wr  is not None else "—")
    r1c3.metric("Avg R-Multiple",  _fmt_r(avg_r))

    r2c1, r2c2, r2c3 = st.columns(3)
    r2c1.metric("Max Drawdown",    f"{dd:.2f}%"     if dd  is not None else "—")
    r2c2.metric("Total PnL",       f"Rs {pnl:,.0f}" if pnl is not None else "—")
    r2c3.metric("Trades / Signals",f"{n_trade} / {n_sig}  ({appr:.0f}%)")

    # Per-strategy table
    per_strat = m.get("per_strategy") or {}
    if per_strat and HAS_PANDAS:
        rows = []
        for name, sv in per_strat.items():
            if isinstance(sv, dict):
                rows.append({
                    "Strategy": name,
                    "Trades":   sv.get("trades", 0),
                    "Win%":     f"{sv.get('win_rate', 0):.1f}%",
                    "Avg R":    _fmt_r(sv.get("avg_r")),
                })
        if rows:
            st.caption("Per-Strategy Breakdown")
            st.dataframe(pd.DataFrame(rows), hide_index=True, use_container_width=True)

# ── Panel 2: Market Capture Ratio ────────────────────────────────────────────
with col2:
    st.subheader("Panel 2 — Market Capture Ratio")

    mcr     = data.get("mcr") or {}
    overall = mcr.get("overall_capture_pct")
    primary = mcr.get("primary_regime") or "—"
    avoid   = mcr.get("avoid_regime")   or "—"
    r_stats = mcr.get("regime_stats")   or []

    if overall is not None:
        st.metric(
            "Overall Capture",
            f"{overall:+.1f}%",
            delta=_capture_label(overall),
        )

    mc1, mc2 = st.columns(2)
    mc1.metric("Best Regime",  primary)
    mc2.metric("Avoid Regime", avoid)

    if r_stats and HAS_PANDAS:
        df_rows = []
        for rs in r_stats:
            if not isinstance(rs, dict):
                continue
            cap = rs.get("capture_ratio_pct")
            df_rows.append({
                "Regime":    rs.get("regime", "?"),
                "Trades":    rs.get("trades_count", 0),
                "Capture%":  round(cap, 1) if cap is not None else 0.0,
                "Win%":      round(rs.get("win_rate", 0), 1),
                "Avg R":     _fmt_r(rs.get("avg_trade_capture")),
            })
        if df_rows:
            df_mcr = pd.DataFrame(df_rows)
            st.caption("Capture % by Regime")
            chart_df = df_mcr.set_index("Regime")[["Capture%"]]
            st.bar_chart(chart_df)
            st.dataframe(df_mcr, hide_index=True, use_container_width=True)
    elif not r_stats:
        st.info("No regime data available.  Run a longer replay (≥30 days) for MCR results.")

st.divider()

# ══════════════════════════════════════════════════════════════════════════════
# Row 2 — Edge Half-Life  |  Edge Distribution Map
# ══════════════════════════════════════════════════════════════════════════════
col3, col4 = st.columns(2)

# ── Panel 3: Edge Half-Life ───────────────────────────────────────────────────
with col3:
    st.subheader("Panel 3 — Edge Half-Life")

    ehl        = data.get("ehl") or {}
    ehl_val    = ehl.get("half_life_candles")
    r0         = ehl.get("r_at_zero")
    drift      = ehl.get("per_candle_drift_pct")
    delays     = ehl.get("delays")     or []
    avg_r_d    = ehl.get("avg_r_at_delay") or []
    rec_exp    = ehl.get("recommended_expiry")
    rec_aet    = ehl.get("recommended_aet_wait")
    rec_re     = ehl.get("recommended_reentry_win")
    n_ehl      = ehl.get("total_trades", 0)

    ehl_disp = (f"{ehl_val:.1f} candles ({ehl_val*5:.0f} min)"
                if ehl_val is not None
                else ">6 candles — edge persists beyond test window")

    st.metric("Edge Half-Life", ehl_disp)

    ea1, ea2, ea3 = st.columns(3)
    ea1.metric("R at Delay=0",  _fmt_r(r0))
    ea2.metric("Drift/Candle",  f"{drift:.4f}%" if drift is not None else "—")
    ea3.metric("Rec Expiry",    f"{rec_exp}c"   if rec_exp is not None else "—")

    if delays and avg_r_d and HAS_PANDAS:
        df_ehl = pd.DataFrame({
            "Candle Delay": [f"{d}c ({d*5}m)" for d in delays],
            "Avg R-Multiple": avg_r_d,
        }).set_index("Candle Delay")
        st.caption("R-Multiple Decay vs Entry Delay")
        st.line_chart(df_ehl)

    st.caption("Calibration vs Current Execution Parameters")
    cal_rows = [
        {"Parameter": "LIMIT_CANDLE_EXPIRY",    "Current": "3c",  "Recommended": f"{rec_exp}c"  if rec_exp  is not None else "—"},
        {"Parameter": "AET_MAX_WAIT_CANDLES",   "Current": "2c",  "Recommended": f"{rec_aet}c"  if rec_aet  is not None else "—"},
        {"Parameter": "REENTRY_WINDOW_CANDLES", "Current": "10c", "Recommended": f"{rec_re}c"   if rec_re   is not None else "—"},
    ]
    if HAS_PANDAS:
        st.dataframe(pd.DataFrame(cal_rows), hide_index=True, use_container_width=True)

# ── Panel 4: Edge Distribution Map ────────────────────────────────────────────
with col4:
    st.subheader("Panel 4 — Edge Distribution Map")

    edm       = data.get("edm") or {}
    profile   = edm.get("profile",            "—")
    win_rate_e= edm.get("win_rate")
    payoff    = edm.get("payoff_ratio")
    tail      = edm.get("tail_profit_ratio")
    loss_conc = edm.get("loss_concentration")
    avg_r_all = edm.get("avg_r")
    bins      = edm.get("bins")     or []
    n_edm     = edm.get("total_trades", 0)

    st.metric(
        "Edge Profile", profile,
        delta=("Tight SL critical" if profile == "Mean-Reversion"
               else ("Let winners run" if profile == "Trend-Following"
               else "Balanced approach")),
    )

    ed1, ed2, ed3 = st.columns(3)
    ed1.metric("Win Rate",    f"{win_rate_e:.1f}%" if win_rate_e is not None else "—")
    ed2.metric("Payoff Ratio",f"{payoff:.2f}x"     if payoff     is not None else "—")
    ed3.metric("Tail Ratio",  f"{tail:.2f}x"       if tail       is not None else "—")

    desc = edm.get("profile_description", "")
    if desc:
        st.caption(desc[:200] + ("…" if len(desc) > 200 else ""))

    active_bins = [b for b in bins if isinstance(b, dict) and b.get("count", 0) > 0]
    if active_bins and HAS_PANDAS:
        df_edm = pd.DataFrame({
            "R Bucket": [b["label"] for b in active_bins],
            "Trades":   [b["count"] for b in active_bins],
        }).set_index("R Bucket")
        st.caption("R-Multiple Frequency Distribution")
        st.bar_chart(df_edm)

        lc_note = ("clustered risk — review SL logic" if loss_conc and loss_conc > 60
                   else "healthy spread")
        st.metric(
            "Loss Concentration (worst 25%)",
            f"{loss_conc:.0f}%"  if loss_conc is not None else "—",
            delta=lc_note,
        )
    elif n_edm == 0:
        st.info("No trade data for distribution analysis.")

st.divider()

# ══════════════════════════════════════════════════════════════════════════════
# Row 3 — Volatility Stability  |  System Health
# ══════════════════════════════════════════════════════════════════════════════
col5, col6 = st.columns(2)

# ── Panel 5: Volatility Stability ────────────────────────────────────────────
with col5:
    st.subheader("Panel 5 — Volatility Stability")

    vix_stab   = data.get("vix_stability") or []
    active_vix = [v for v in vix_stab if (v.get("trades") or 0) > 0]

    if active_vix and HAS_PANDAS:
        df_vix = pd.DataFrame(active_vix)
        chart_df = df_vix.set_index("label")[["avg_r"]].rename(
            columns={"avg_r": "Avg R-Multiple"}
        )
        st.caption("Avg R-Multiple by VIX Band")
        st.bar_chart(chart_df)

        disp_rows = []
        for row in vix_stab:
            disp_rows.append({
                "VIX Band": row["label"],
                "Trades":   row.get("trades", 0),
                "Avg R":    _fmt_r(row.get("avg_r")),
                "Win%":     _fmt_pct(row.get("win_rate")),
                "PF":       f"{row['pf']:.2f}" if row.get("pf") is not None else "—",
            })
        st.dataframe(pd.DataFrame(disp_rows), hide_index=True, use_container_width=True)

        extreme_r = next(
            (r.get("avg_r") for r in vix_stab if "Extreme" in r["label"]), None
        )
        if extreme_r is not None and extreme_r < 0:
            st.warning(
                "Edge is **negative** in Extreme VIX (>25).  "
                "Consider auto-disabling strategies when VIX > 25."
            )
        elif extreme_r is not None and extreme_r < 0.2:
            st.info(
                "Edge degrades significantly above VIX 25.  "
                "Reduce position sizing in high-volatility sessions."
            )
        else:
            st.success("Edge is stable across all tested VIX bands.")
    else:
        st.info(
            "Insufficient trades spread across VIX bands.  "
            "Run a longer replay to populate this panel."
        )

# ── Panel 6: System Health ────────────────────────────────────────────────────
with col6:
    st.subheader("Panel 6 — System Health")

    health  = data.get("health")  or {}
    n_err   = health.get("total_errors",     0)
    d_err   = health.get("days_with_errors", 0)
    d_trade = health.get("days_with_trades", 0)
    d_total = health.get("total_days",       1) or 1

    h1, h2 = st.columns(2)
    h1.metric("Pipeline Errors",   str(n_err),
              delta="OK" if n_err == 0 else f"{n_err} issue(s)")
    h2.metric("Days with Errors",  f"{d_err} / {d_total}")

    h3, h4 = st.columns(2)
    h3.metric("Days with Trades",  f"{d_trade} / {d_total}")
    density = d_trade / d_total * 100
    h4.metric("Trade Density",     f"{density:.0f}%")

    # Monte Carlo risk (stored in 'mc' key)
    mc_data = data.get("mc") or {}
    ruin    = mc_data.get("ruin_probability")
    p95dd   = mc_data.get("p95_max_dd")
    mc_verd = mc_data.get("verdict")

    frag_d  = data.get("frag") or {}
    frag_vd = frag_d.get("verdict")

    st.caption("Risk & Execution Indicators")
    indicators = [
        ("Pipeline Errors",   "OK" if n_err == 0 else f"WARN — {n_err} error(s)"),
        ("Ruin Probability",  f"{ruin:.1f}%"  if ruin   is not None else "—"),
        ("MC p95 Drawdown",   f"{p95dd:.1f}%" if p95dd  is not None else "—"),
        ("MC Verdict",        mc_verd        if mc_verd is not None else "—"),
        ("Fragility",         frag_vd        if frag_vd is not None else "—"),
        ("Risk Violations",   "0"),
        ("Order Mode",        "PAPER TRADING"),
    ]
    for name, val in indicators:
        ok   = val in ("OK", "0", "PAPER TRADING") or (
            isinstance(val, str) and any(x in val.upper() for x in ("ROBUST", "STABLE"))
        )
        warn = isinstance(val, str) and any(
            x in val.upper() for x in ("WARN", "FRAGILE", "CRIT", "NO-GO")
        )
        icon = "✅" if ok else ("⚠️" if warn else "ℹ️")
        st.markdown(f"{icon}  **{name}**: `{val}`")

    # ── GO / NO-GO verdict ────────────────────────────────────────────────────
    st.divider()
    no_go: List[str] = []
    if n_err > 0:
        no_go.append(f"{n_err} pipeline error(s) detected")
    pf_v = _safe(data, "metrics", "profit_factor") or 0.0
    wr_v = _safe(data, "metrics", "win_rate")      or 0.0
    if pf_v < 1.0:
        no_go.append(f"Profit Factor {pf_v:.2f} < 1.0 — system is unprofitable")
    if wr_v < 40:
        no_go.append(f"Win rate {wr_v:.1f}% < 40% — too many losses")
    if ruin is not None and ruin > 5.0:
        no_go.append(f"Ruin probability {ruin:.1f}% > 5% — excessive risk")

    if no_go:
        st.error(
            "🔴 **NO-GO for live capital**\n\n" +
            "\n".join(f"- {r}" for r in no_go)
        )
    else:
        st.success(
            "🟢 **GO — System cleared all edge diagnostics checks.**  "
            "Edge is positive, stable, and risk-controlled."
        )

st.divider()

# ── Strategy edge profile table (from EDM per-strategy data) ─────────────────
edm_strats = (data.get("edm") or {}).get("per_strategy") or {}
if edm_strats and HAS_PANDAS:
    st.subheader("Strategy Edge Profiles")
    s_rows = []
    for name, sp in edm_strats.items():
        if isinstance(sp, dict):
            s_rows.append({
                "Strategy":    sp.get("strategy", name),
                "Trades":      sp.get("trades",       0),
                "Win%":        f"{sp.get('win_rate', 0):.1f}%",
                "Avg R":       _fmt_r(sp.get("avg_r")),
                "Payoff":      f"{sp.get('payoff_ratio', 0):.2f}x",
                "Profile":     sp.get("profile", "—"),
            })
    if s_rows:
        s_rows_sorted = sorted(s_rows, key=lambda x: -x["Trades"])
        st.dataframe(pd.DataFrame(s_rows_sorted), hide_index=True, use_container_width=True)

# ── Footer ─────────────────────────────────────────────────────────────────────
gen_ago = ""
if gen_at:
    secs = (datetime.now() - datetime.fromisoformat(gen_at)).total_seconds()
    if secs < 3600:
        gen_ago = f" — {secs / 60:.0f} min ago"
    else:
        gen_ago = f" — {secs / 3600:.1f} h ago"

st.caption(
    f"Data: `{SUMMARY_PATH.relative_to(_ROOT)}`{gen_ago}  ·  "
    "Press **R** in browser to reload  ·  "
    "AI Trading Brain — Edge Diagnostics Suite  ·  "
    "AET | MCR | EHL | EDM"
)
