"""
scripts/knowledge_system/knowledge_feedback_loop_001.py
========================================================
Central orchestrator — Knowledge System Autonomous Research Loop KSL-001.

Runs all stages in sequence:
  1. INGEST          — consume new shadow records
  2. CLASSIFY        — evidence records classified (done inside consumer)
  3. DETECT PATTERNS — mine evidence ledger
  4. GENERATE RQs    — patterns → research questions
  5. PRIORITIZE      — score and rank questions
  6. BUILD PROPOSALS — proposals for top questions
  7. HYPOTHESIS INTEGRATION — register top questions in hypothesis_registry
  8. RECORD          — knowledge evidence ledger updated throughout
  9. STATE UPDATE    — save processing state

All writes are append-only.
Zero production mutations: no broker calls, no orders, no CandidateStore.
"""
from __future__ import annotations

import json
import os
import sys
import uuid
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Dict, List, Optional

ROOT = Path(__file__).resolve().parent.parent.parent
sys.path.insert(0, str(ROOT))

from scripts.knowledge_system.shadow_evidence_consumer_001 import consume_new_records, seed_from_historical_audit_csv
from scripts.knowledge_system.knowledge_pattern_miner_001 import mine_patterns
from scripts.knowledge_system.research_question_generator_001 import generate_questions
from scripts.knowledge_system.research_priority_engine_001 import prioritize_questions
from scripts.knowledge_system.research_proposal_builder_001 import build_proposals_for_top_n
from scripts.knowledge_system.ksl_models import (
    EvidenceRecord,
    KSLEventType,
    KSLState,
    PatternRecord,
    ResearchQuestion,
    ResearchProposal,
)

# Paths
KNOWLEDGE_LEDGER    = ROOT / "data" / "knowledge_evidence_ledger.jsonl"
RQ_QUEUE_PATH       = ROOT / "data" / "research_question_queue.jsonl"
STATE_JSON          = ROOT / "data" / "ksl" / "knowledge_system_state.json"
RESEARCH_QUEUE_JSON = ROOT / "data" / "ksl" / "knowledge_system_research_queue.json"


# ─────────────────────────────────────────────────────────────────────────────
# Hypothesis registry integration (optional — gracefully skips if unavailable)
# ─────────────────────────────────────────────────────────────────────────────


def _try_register_hypothesis(rq: ResearchQuestion) -> Optional[str]:
    """
    Attempt to create a PROPOSED hypothesis in the registry for a high-priority RQ.
    Returns hypothesis_id or None if registration failed (non-fatal).
    """
    try:
        from autonomous_research.knowledge_provider import KnowledgeProvider
        from autonomous_research.hypothesis_registry import HypothesisRegistry
        from autonomous_research.hypothesis_models import (
            HypothesisClassification,
            HypothesisPriority,
            HypothesisStatus,
        )

        kp = KnowledgeProvider()
        hr = HypothesisRegistry(knowledge_provider=kp)

        # Map RQ priority to hypothesis priority
        if rq.research_priority >= 80:
            priority = HypothesisPriority.CRITICAL
        elif rq.research_priority >= 60:
            priority = HypothesisPriority.HIGH
        elif rq.research_priority >= 40:
            priority = HypothesisPriority.MEDIUM
        else:
            priority = HypothesisPriority.LOW

        h = hr.create_hypothesis(
            title=f"KSL-001 Auto: {rq.problem_area.value} — {rq.direction}",
            research_question=rq.question[:500],
            description=(
                f"Automatically generated by KSL-001 from pattern detection. "
                f"Problem area: {rq.problem_area.value}. Direction: {rq.direction}. "
                f"Regime scope: {rq.regime_scope}. "
                f"Priority score: {rq.research_priority}/100. "
                f"Source question ID: {rq.research_question_id}."
            ),
            origin="KSL_AUTO",
            priority=priority,
            classification=HypothesisClassification.PERFORMANCE_GAP,
            knowledge_gap=f"RQ: {rq.research_question_id}",
            expected_knowledge_gain="Improve Top-5 ge2_rate in OOS period",
            validation_method=f"Train/Val/OOS on post_open_gap_analysis.csv; leakage check required",
            supporting_evidence=[],
            origin_study="KSL-001",
            created_by="KSL_AUTO",
            confidence=min(rq.research_priority / 100 * 0.7, 0.7),
            required_data=rq.required_data,
            notes=rq.notes,
        )
        return h.hypothesis_id
    except Exception:
        return None  # non-fatal


# ─────────────────────────────────────────────────────────────────────────────
# Loop runner
# ─────────────────────────────────────────────────────────────────────────────


def run_loop(
    register_hypotheses: bool = True,
    top_n_proposals: int = 3,
    min_proposal_priority: float = 55.0,
    seed_historical: bool = True,
) -> Dict[str, Any]:
    """
    Run one complete KSL-001 feedback loop iteration.
    Returns a summary dict with counts and top research questions.
    """
    run_id = str(uuid.uuid4())
    started_at = datetime.now(timezone.utc).isoformat()
    summary: Dict[str, Any] = {
        "run_id": run_id,
        "started_at": started_at,
        "safety": {
            "broker_calls": 0,
            "orders": 0,
            "candidatestore_writes": 0,
            "production_changes": 0,
        },
    }

    KNOWLEDGE_LEDGER.parent.mkdir(parents=True, exist_ok=True)
    STATE_JSON.parent.mkdir(parents=True, exist_ok=True)

    # ── STAGE 0: HISTORICAL SEED (one-time bootstrap) ─────────────────────
    if seed_historical:
        seeded = seed_from_historical_audit_csv()
        summary["seeded_historical_records"] = len(seeded)
        if seeded:
            _log_event({"event_type": "LOOP_STAGE", "stage": "HISTORICAL_SEED",
                        "seeded": len(seeded), "run_id": run_id})
            print(f"[KSL] Stage 0: Historical seed — {len(seeded)} records.")

    # ── STAGE 1 + 2: INGEST & CLASSIFY ────────────────────────────────────
    print("[KSL] Stage 1/2: Shadow evidence ingestion + classification …")
    new_evidence: List[EvidenceRecord] = consume_new_records()
    summary["new_evidence_records"] = len(new_evidence)
    _log_event({"event_type": "LOOP_STAGE", "stage": "INGEST", "new_records": len(new_evidence), "run_id": run_id})
    print(f"       {len(new_evidence)} new records ingested.")

    # ── STAGE 3: DETECT PATTERNS ──────────────────────────────────────────
    print("[KSL] Stage 3: Pattern mining …")
    patterns: List[PatternRecord] = mine_patterns()
    summary["patterns_detected"] = len(patterns)
    _log_event({"event_type": "LOOP_STAGE", "stage": "PATTERN_MINE", "patterns": len(patterns), "run_id": run_id})
    for p in patterns:
        _log_event({
            "event_type": KSLEventType.PATTERN.value,
            "pattern_id": p.pattern_id,
            "pattern_type": p.pattern_type.value,
            "direction": p.direction,
            "strength": p.strength,
            "description": p.description,
            "run_id": run_id,
        })
    print(f"       {len(patterns)} patterns detected.")

    # ── STAGE 4: GENERATE RESEARCH QUESTIONS ──────────────────────────────
    print("[KSL] Stage 4: Research question generation …")
    new_questions: List[ResearchQuestion] = generate_questions(patterns)
    summary["new_questions_generated"] = len(new_questions)
    _log_event({"event_type": "LOOP_STAGE", "stage": "GENERATE_RQ", "questions": len(new_questions), "run_id": run_id})
    print(f"       {len(new_questions)} new research questions generated.")

    # ── STAGE 5: PRIORITIZE ───────────────────────────────────────────────
    print("[KSL] Stage 5: Prioritization …")
    all_questions = _load_all_questions()
    prioritized = prioritize_questions(all_questions, patterns)
    summary["total_questions_in_queue"] = len(prioritized)
    print(f"       {len(prioritized)} total questions in queue.")

    # ── STAGE 6: BUILD PROPOSALS ──────────────────────────────────────────
    print("[KSL] Stage 6: Research proposal building …")
    proposals: List[ResearchProposal] = build_proposals_for_top_n(
        prioritized,
        n=top_n_proposals,
        min_priority=min_proposal_priority,
    )
    summary["proposals_built"] = len(proposals)
    for prop in proposals:
        _log_event({
            "event_type": KSLEventType.RESEARCH_PROPOSAL.value,
            "proposal_id": prop.proposal_id,
            "question_id": prop.research_question_id,
            "run_id": run_id,
        })
    print(f"       {len(proposals)} research proposals built.")

    # ── STAGE 7: HYPOTHESIS REGISTRY INTEGRATION ─────────────────────────
    registered: List[str] = []
    if register_hypotheses and new_questions:
        print("[KSL] Stage 7: Hypothesis registry integration …")
        for rq in new_questions:
            if rq.research_priority >= min_proposal_priority:
                hyp_id = _try_register_hypothesis(rq)
                if hyp_id:
                    registered.append(hyp_id)
        print(f"       {len(registered)} hypotheses registered.")
    summary["hypotheses_registered"] = len(registered)

    # ── STAGE 8: SAVE STATE & OUTPUTS ─────────────────────────────────────
    print("[KSL] Stage 8: Saving state and output files …")
    _save_state_json(summary, run_id, started_at, patterns, prioritized, proposals)
    _save_research_queue_json(prioritized[:20])  # top 20 in machine-readable format

    completed_at = datetime.now(timezone.utc).isoformat()
    summary["completed_at"] = completed_at
    summary["top_questions"] = [
        {
            "rank": i + 1,
            "id": q.research_question_id,
            "priority": q.research_priority,
            "area": q.problem_area.value,
            "direction": q.direction,
            "question": q.question[:200],
        }
        for i, q in enumerate(prioritized[:5])
    ]

    _log_event({
        "event_type": "LOOP_COMPLETE",
        "run_id": run_id,
        "started_at": started_at,
        "completed_at": completed_at,
        "new_evidence": len(new_evidence),
        "patterns": len(patterns),
        "new_questions": len(new_questions),
        "proposals": len(proposals),
    })

    # ── STAGE 9: WRITE HEALTH FILE ────────────────────────────────────────
    try:
        write_health_file(summary)
    except Exception as _hf_exc:
        print(f"[KSL] Health file write failed (non-critical): {_hf_exc}")

    print(f"[KSL] Complete. Run: {run_id}")
    return summary


# ─────────────────────────────────────────────────────────────────────────────
# Helpers
# ─────────────────────────────────────────────────────────────────────────────


def _log_event(event: Dict) -> None:
    KNOWLEDGE_LEDGER.parent.mkdir(parents=True, exist_ok=True)
    with open(KNOWLEDGE_LEDGER, "a") as f:
        f.write(json.dumps(event) + "\n")


def _load_all_questions() -> List[ResearchQuestion]:
    if not RQ_QUEUE_PATH.exists():
        return []
    questions = []
    from scripts.knowledge_system.ksl_models import ResearchQuestionStatus
    with open(RQ_QUEUE_PATH) as f:
        for line in f:
            try:
                d = json.loads(line)
                rq = ResearchQuestion(
                    research_question_id=d["research_question_id"],
                    created_at=d.get("created_at", ""),
                    source_pattern_ids=d.get("source_pattern_ids", []),
                    question=d.get("question", ""),
                    problem_area=d.get("problem_area", "OTHER"),
                    direction=d.get("direction", "BOTH"),
                    regime_scope=d.get("regime_scope", "ALL"),
                    baseline=d.get("baseline", ""),
                    candidate_change=d.get("candidate_change", ""),
                    target_metric=d.get("target_metric", ""),
                    minimum_sample=d.get("minimum_sample", 100),
                    required_data=d.get("required_data", []),
                    known_data_gaps=d.get("known_data_gaps", []),
                    leakage_risk=d.get("leakage_risk", "LOW"),
                    research_priority=d.get("research_priority", 0.0),
                    status=ResearchQuestionStatus(d.get("status", "GENERATED")),
                    duplicate_of=d.get("duplicate_of"),
                    notes=d.get("notes", ""),
                )
                # Skip superseded
                from scripts.knowledge_system.ksl_models import ResearchArea
                try:
                    rq.problem_area = ResearchArea(d.get("problem_area", "OTHER"))
                except ValueError:
                    rq.problem_area = ResearchArea.OTHER
                if rq.status != ResearchQuestionStatus.SUPERSEDED:
                    questions.append(rq)
            except (KeyError, json.JSONDecodeError):
                pass
    return questions


def _save_state_json(summary: Dict, run_id: str, started_at: str,
                     patterns: List, questions: List, proposals: List) -> None:
    state = {
        "last_run_id": run_id,
        "last_run_at": started_at,
        "completed_at": summary.get("completed_at", ""),
        "total_evidence_records": summary.get("new_evidence_records", 0),
        "total_patterns_detected": len(patterns),
        "total_questions_in_queue": len(questions),
        "total_proposals_built": len(proposals),
        "safety": summary["safety"],
        "top_patterns": [
            {"type": p.pattern_type.value, "direction": p.direction,
             "strength": p.strength, "description": p.description}
            for p in patterns[:5]
        ],
    }
    tmp = STATE_JSON.with_suffix(".tmp")
    with open(tmp, "w") as f:
        json.dump(state, f, indent=2)
    os.replace(tmp, STATE_JSON)


def _save_research_queue_json(questions: List[ResearchQuestion]) -> None:
    queue = {
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "top_research_questions": [
            {
                "rank": i + 1,
                "research_question_id": q.research_question_id,
                "priority": q.research_priority,
                "area": q.problem_area.value,
                "direction": q.direction,
                "regime_scope": q.regime_scope,
                "question": q.question,
                "candidate_change": q.candidate_change,
                "target_metric": q.target_metric,
                "status": q.status.value,
            }
            for i, q in enumerate(questions)
        ],
    }
    RESEARCH_QUEUE_JSON.parent.mkdir(parents=True, exist_ok=True)
    tmp = RESEARCH_QUEUE_JSON.with_suffix(".tmp")
    with open(tmp, "w") as f:
        json.dump(queue, f, indent=2)
    os.replace(tmp, RESEARCH_QUEUE_JSON)


# ─────────────────────────────────────────────────────────────────────────────
# Knowledge pipeline health file
# ─────────────────────────────────────────────────────────────────────────────

HEALTH_PATH = ROOT / "data" / "knowledge_pipeline_health.json"
_STALE_ALERT_PATH = ROOT / "data" / "knowledge_pipeline_health.last_stale_alert"
_STALE_HOURS = 48  # pipeline is "stale" if not run in this many hours
_STALE_ALERT_COOLDOWN_H = 24  # only send one stale alert per this many hours


def write_health_file(summary: Dict) -> None:
    """
    Write data/knowledge_pipeline_health.json after every run_loop() call.
    Includes counts, last-run timestamp, staleness flag, and overall status.
    Sends a Telegram alert (rate-limited to once per 24 h) when the pipeline
    has been stale for more than STALE_HOURS hours.
    """
    from scripts.knowledge_system.shadow_evidence_consumer_001 import (
        SHADOW_JSONL,
        LEDGER_PATH,
        STATE_PATH,
    )

    now = datetime.now(timezone.utc)

    # Ledger sizes
    evidence_count = sum(1 for _ in open(LEDGER_PATH)) if LEDGER_PATH.exists() else 0
    knowledge_count = sum(1 for _ in open(KNOWLEDGE_LEDGER)) if KNOWLEDGE_LEDGER.exists() else 0
    rq_count = sum(1 for _ in open(RQ_QUEUE_PATH)) if RQ_QUEUE_PATH.exists() else 0

    # Shadow source info
    shadow_size = SHADOW_JSONL.stat().st_size if SHADOW_JSONL.exists() else 0
    shadow_lines = sum(1 for _ in open(SHADOW_JSONL)) if SHADOW_JSONL.exists() else 0

    # Last run from KSL state file (authoritative: set by consumer)
    last_run_at = summary.get("completed_at", "")
    byte_offset = 0
    if STATE_PATH.exists():
        try:
            _st = json.loads(STATE_PATH.read_text())
            byte_offset = _st.get("last_processed_byte_offset", 0)
            if not last_run_at:
                last_run_at = _st.get("last_processed_at", "")
        except Exception:
            pass

    # Staleness calculation
    pipeline_age_hours: Optional[float] = None
    stale = False
    if last_run_at:
        try:
            _lr = datetime.fromisoformat(last_run_at.replace("Z", "+00:00"))
            if _lr.tzinfo is None:
                _lr = _lr.replace(tzinfo=timezone.utc)
            pipeline_age_hours = round((now - _lr).total_seconds() / 3600, 1)
            stale = pipeline_age_hours > _STALE_HOURS
        except Exception:
            pass

    overall_status = (
        "STALE" if stale else ("OK" if evidence_count > 0 else "NO_DATA")
    )

    health = {
        "audit_timestamp": now.isoformat(),
        "shadow_source": str(SHADOW_JSONL),
        "shadow_file_size_bytes": shadow_size,
        "shadow_records_available": shadow_lines,
        "shadow_bytes_consumed": byte_offset,
        "evidence_records": evidence_count,
        "knowledge_events": knowledge_count,
        "research_questions": rq_count,
        "new_evidence_this_run": summary.get("new_evidence_records", 0),
        "patterns_this_run": summary.get("patterns_detected", 0),
        "new_questions_this_run": summary.get("new_questions_generated", 0),
        "proposals_this_run": summary.get("proposals_built", 0),
        "pipeline_last_run": last_run_at,
        "pipeline_age_hours": pipeline_age_hours,
        "stale": stale,
        "overall_status": overall_status,
    }

    HEALTH_PATH.parent.mkdir(parents=True, exist_ok=True)
    tmp = HEALTH_PATH.with_suffix(".tmp")
    with open(tmp, "w") as _f:
        json.dump(health, _f, indent=2)
    os.replace(tmp, HEALTH_PATH)

    # Rate-limited stale alert via Telegram (max once per STALE_ALERT_COOLDOWN_H)
    if stale:
        try:
            _send = True
            if _STALE_ALERT_PATH.exists():
                _last_ts = datetime.fromisoformat(_STALE_ALERT_PATH.read_text().strip())
                if _last_ts.tzinfo is None:
                    _last_ts = _last_ts.replace(tzinfo=timezone.utc)
                if (now - _last_ts).total_seconds() < _STALE_ALERT_COOLDOWN_H * 3600:
                    _send = False
            if _send:
                from notifications import get_notifier
                get_notifier().send_alert(
                    f"[KSL-001] Knowledge pipeline STALE: "
                    f"{pipeline_age_hours}h since last run. "
                    f"Shadow source has {shadow_lines} records "
                    f"({shadow_size} bytes). "
                    f"Check that orchestrator EOD cycle is running."
                )
                _STALE_ALERT_PATH.write_text(now.isoformat())
        except Exception:
            pass  # notification is best-effort


if __name__ == "__main__":
    summary = run_loop()
    print("\n=== KSL-001 RESEARCH AGENDA ===")
    for q in summary.get("top_questions", []):
        print(f"  [{q['rank']}] Priority={q['priority']}/100  [{q['area']} / {q['direction']}]")
        print(f"      {q['question'][:200].encode('ascii', errors='replace').decode()}")
        print()
